### ISSUE TITLE
'PyEval_CallObjectWithKeywords': deprecated in 3.9 - fails to build ORT pyop bindings

### ISSUE THREAD

**Issue by nkreeger** [microsoft/onnxruntime#9736]
While setting up a new build machine - I noticed that ORT fails to build with Python 3.10. 

Build command:
```
.\build.bat --config Debug --enable_pybind --enable_language_interop_ops --enable_training --build_wheel --parallel --skip_tests --enable_training_torch_interop --cmake_generator "Visual Studio 17 2022"
```

Build exception:
```
C:\Users\nickkreeger\src\onnxruntime\onnxruntime\core\language_interop_ops\pyop\pyop.cc(212,21): error C4996: 'PyEval_CallObjectWithKeywords': deprecated in 3.9 [C:\Users\nickkreeger\src\onnxruntime\build\Windows\Debug\onnxruntime_pyop
.vcxproj]
```

It looks like we need to update the C API from a deprecated `PyEval*` call as outlined here:
https://docs.python.org/3/whatsnew/3.9.html#changes-in-the-c-api
https://docs.python.org/3/c-api/call.html#c.PyObject_Call
