### ISSUE TITLE
[Build]: Test fails with gcc 11 and Build fails with gcc 12/13 on ROCm.

### ISSUE THREAD

**Issue by lshqqytiger** [microsoft/onnxruntime#18155]
### Describe the issue

I'm trying to build onnxruntime 1.16.1 with ROCm 5.6.
When I tried first, it failed with `librt.so` not found error.
But I had `librt.so.1` and was not able to find any solution, I copied it as `librt.so`.
Then, the build finished but first 3 tests are failed with `"GLIBCXX_3.4.30" not found`.
I searched out and found out this may be due to the version of GCC.
So I installed gcc-12 but it failed building with the error I attached.
With gcc-13, I got same error.
How can I build onnxruntime for ROCm properly?

### Target platform

Ubuntu 22.04.3 ROCm 5.6

### Build script

```
git clone https://github.com/microsoft/onnxruntime
cd onnxruntime
git checkout tags/v1.16.1
./build.sh --config Release --use_rocm --rocm_home /opt/rocm
```

### Error / output

```
...
[ 37%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/user/stable-diffusion/ort_build/onnxruntime/onnxruntime/core/providers/cpu/tensor/scatter.cc.o
In function ‘onnxruntime::common::Status onnxruntime::ScatterData(const FuncT&, const Tensor*, const std::vector<long int>&, const Tensor*, int64_t, Tensor*) [with Tdata = bool; FuncT = Func_Assignment<bool>]’:
/home/user/stable-diffusion/ort_build/onnxruntime/onnxruntime/core/providers/cpu/tensor/scatter.cc:343:25: error: array subscript -1 is outside array bounds of ‘long int [1152921504606846975]’ [-Werror=array-bounds=]
  343 |   dim_block_size.back() = 1;
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~
... (similar errors are continued)
```

### Visual Studio Version

No visual studio installed.

### GCC / Compiler Version

GCC 11.4.0, 12.3.0, 13.1.0

**Comment by PeixuanZuo** [comment]
Could you please refer to this [Dockerfile ](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/pai/rocm-ci-pipeline-env.Dockerfile#L76)(This Dockerfile is build with Ubuntu22.04  ROCm5.7, please change the ROCM_VERSION to 5.6)

**Comment by lshqqytiger** [comment]
I get this error while building and installing transformers.
```
      warning: `tokenizers` (lib) generated 6 warnings
      error: could not compile `tokenizers` (lib) due to previous error; 6 warnings emitted
```

rustc:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
```

**Comment by PeixuanZuo** [comment]
You don't need to run all commands in  [Dockerfile ](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/pai/rocm-ci-pipeline-env.Dockerfile), commands before [L84](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/pai/rocm-ci-pipeline-env.Dockerfile#L84) is enough.

**Comment by lshqqytiger** [comment]
I followed them, but the same `"GLIBCXX_3.4.30" not found` error occurred in the same 3 tests.
Should I use gcc 12 or 13?

**Comment by cloudhan** [comment]
I am suspecting that you are using conda/miniconda in your dev environment for python and you are using gcc from your host machine (/usr), then you might encounter `GLIBCXX_3.4.30`. The reason is the linked version stdc++ library is the new version from /usr at build time, and it resolves to old version from conda environment. You can follow this https://stackoverflow.com/a/73708979 to workaround it.

**Comment by PeixuanZuo** [comment]
Or you can choose to use gcc12/13 with this [PR](https://github.com/microsoft/onnxruntime/pull/18178)(cherry-pick the commit to your branch).

**Comment by lshqqytiger** [comment]
> I am suspecting that you are using conda/miniconda in your dev environment for python and you are using gcc from your host machine (/usr), then you might encounter `GLIBCXX_3.4.30`. The reason is the linked stdc++ library is the new version from /usr at build time, and it resolves to old version from conda environment. You can follow this https://stackoverflow.com/a/73708979 to workaround it.

I followed this solution and I have `GLIBCXX_3.4.30` on my virtual environment.
But I got same error.
```
$ strings ~/anaconda3/envs/ort_build/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
GLIBCXX_3.4.32
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Should I install another gcc in conda environment? or use docker..or use gcc 12..

**Comment by snnn** [comment]
As you already have libstdc++.so.6 in your conda env, you need to use the compilers(gcc/g++) that comes from conda, and only run the built binary in conda . 
Or you choose to not do the build in conda.

**Comment by snnn** [comment]
In the description of this issue you listed three different GCC versions:
```
GCC 11.4.0, 12.3.0, 13.1.0
```
Only one of them is relevant. You need to figure out which one was actually used.

**Comment by lshqqytiger** [comment]
> As you already have libstdc++.so.6 in your conda env, you need to use the compilers(gcc/g++) that comes from conda, and only run the built binary in conda . 
> Or you choose to not do the build in conda. 

I have tried to build without activating conda environment, I could get the same error.

**Comment by lshqqytiger** [comment]
> In the description of this issue you listed three different GCC versions:
> ```
> GCC 11.4.0, 12.3.0, 13.1.0
> ```
> Only one of them is relevant. You need to figure out which one was actually used. 

I tried all of them. Until now, I was using 11.4.0. I'll try with 12.3.0 and your PR.

**Comment by lshqqytiger** [comment]
It appeared to pass the test but failed in the last testcase. I can get `ROCMExecutionProvider` with `onnxruntime-training` built with ROCm and I no longer need to build it myself. Thank you for all your help.
