### ISSUE TITLE
Regression: "ceil_mode_" is not defined

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#903]
**Describe the bug**

Get the following error today.
Git blame says it's probably a regression caused by PR #873 
If so, can someone also add the CI coverage?

```
/tmp/scratch/onnxruntime/onnxruntime/core/providers/mkldnn/nn/pool.cc:257:103: error: 'ceil_mode_' was not declared in this scope
   std::vector<int64_t> y_dims = PoolBase::SetOutputSize(x_shape, x_shape[1], &pads, this->dilations_, ceil_mode_);
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.6
- GCC/Compiler version (if compiling from source): gcc 8.2.0

**Comment by pranavsharma** [comment]
Please specify the build command you used so that it helps us debug faster. Thx.

**Comment by xkszltl** [comment]
Not necessary (come on...the file name is there...) but sure:

https://github.com/xkszltl/Roaster/blob/70641011b532b2e911ed15f93d9615f6da196301/pkgs/ort.sh#L52-L53
https://github.com/xkszltl/Roaster/blob/70641011b532b2e911ed15f93d9615f6da196301/pkgs/ort.sh#L66-L100
```
export CC="gcc-8" CXX="g++-8"
cmake                                               \
    -DCMAKE_BUILD_TYPE=Release                      \
    -DCMAKE_C_COMPILER="$CC"                        \
    -DCMAKE_CXX_COMPILER="$CXX"                     \
    -DCMAKE_{C,CXX,CUDA}_COMPILER_LAUNCHER=ccache   \
    -DCMAKE_C{,XX}_FLAGS="-fdebug-prefix-map='$SCRATCH'='$INSTALL_PREFIX/src' -g"   \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_ABS"           \
    -DCMAKE_POLICY_DEFAULT_CMP0003=NEW              \
    -DCMAKE_POLICY_DEFAULT_CMP0060=NEW              \
    -DCMAKE_VERBOSE_MAKEFILE=ON                     \
    -Deigen_SOURCE_PATH="/usr/local/include/eigen3" \
    -Donnxruntime_BUILD_FOR_NATIVE_MACHINE=ON       \
    -Donnxruntime_BUILD_SHARED_LIB=ON               \
    -Donnxruntime_CUDNN_HOME='/usr/lib64'           \
    -Donnxruntime_ENABLE_PYTHON=ON                  \
    -Donnxruntime_ENABLE_LTO=OFF                    \
    -Donnxruntime_RUN_ONNX_TESTS=ON                 \
    -Donnxruntime_USE_BRAINSLICE=OFF                \
    -Donnxruntime_USE_CUDA=OFF                      \
    -Donnxruntime_USE_EIGEN_FOR_BLAS=OFF            \
    -Donnxruntime_USE_EIGEN_THREADPOOL=OFF          \
    -Donnxruntime_USE_FULL_PROTOBUF=ON              \
    -Donnxruntime_USE_JEMALLOC=OFF                  \
    -Donnxruntime_USE_LLVM=ON                       \
    -Donnxruntime_USE_MKLDNN=ON                     \
    -Donnxruntime_USE_MKLML=ON                      \
    -Donnxruntime_USE_NSYNC=OFF                     \
    -Donnxruntime_USE_NUPHAR=OFF                    \
    -Donnxruntime_USE_OPENBLAS=ON                   \
    -Donnxruntime_USE_OPENMP=ON                     \
    -Donnxruntime_USE_PREINSTALLED_EIGEN=OFF        \
    -Donnxruntime_USE_TENSORRT=OFF                  \
    -Donnxruntime_USE_TVM=OFF                       \
    -G"Ninja"                                       \
    ../cmake
```

**Comment by jignparm** [comment]
Thank you for reporting. This is fixed now. Please use the updated master.
