### PR TITLE
arm64: fix compilation failed when -mcpu is set by the toolchain

### PR DESCRIPTION
**Pull request by clementperon**
### Description
When building with a cross-toolchain some CXX_FLAGS could be set to a specific CPU.

This leads to a CPU not compatible with some specific functions compiles with ARCH v8.2+bf16

Error is :
cc1: error: switch '-mcpu=XXXX' conflicts with '-march=armv8.2-a+i8mm' switch

### Motivation and Context
As these functions are dispatched at runtime and as there is no -mno-cpu, force the -mcpu to be valid by forcing it to a valid combination of -march and -mcpu

### CODE REVIEW

**Comment by snnn** [comment]
According to https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu, we should not need to use both "-march" and "-mcpu"

**Comment by clementperon** [comment]
@snnn according to your article we should avoid -march and only use -mcpu.

What would you say about only keeping -mcpu in this patch ? This would also fix my issue

**Comment by lida2003** [comment]
Hi, @clementperon, I have met this https://github.com/microsoft/onnxruntime/discussions/23267

Is this patch ok to build without "BFLOAT16" issue?

**Comment by snnn** [comment]
@lida2003 , would you please consider upgrading your jetpack to 6.0(which has Ubuntu 22.04 and GCC 11)?

**Comment by lida2003** [comment]
@snnn We are focusing ROS/ubuntu20.04, Jetpack 5.1.4 is the up to date release for this. JP6 doesn't support this. And I think there are quite a lot of users are ON JP5 now.

**Comment by snnn** [comment]
Even ubuntu20.04 itself will reach EOL in a few months.  Sorry we do not have bandwidth to maintain a build system for ubuntu20.04 and GCC 9.  You may fork this repo and patch it in your way.

**Comment by snnn** [comment]
@liqunfu , I am not familiar with mlas code. If you would like to take the changes, please help review the PR.  Otherwise I will close it later.

**Comment by lida2003** [comment]
> You may fork this repo and patch it in your way.
@snnn That's OK. 

Currently the treads end up here, but the patch is not working. Is there any flags or other links/help available for me?

**Comment by snnn** [comment]
You may search the build flag in https://github.com/microsoft/onnxruntime/blame/main/cmake/onnxruntime_mlas.cmake

**Comment by snnn** [comment]
I believe it was added in #14538

**Comment by clementperon** [comment]
@snnn @lida2003 

There is two issues here:
- first the compiler that should be able to compile this new CPU/ARCH support
- second the compiler that already set some CPU specification

We could either:
- compile these functions and detect at runtime that there will be not used
   This will imply to drop the default C_FLAGS/CXX_FLAGS set by the toolchain
- detect that the toolchain is not compatible and drop these functions.

If we agree and what we want to do I could propose another patch.

**Comment by snnn** [comment]
> compile these functions and detect at runtime that there will be not used

It is what we are doing.

**Comment by snnn** [comment]
Sorry  I am not familiar with this part of code.  We need someone from the @onnxruntime-mlas team to answer this question and review the code.

**Comment by snnn** [comment]
@liqunfu , would you be able to help?

**Comment by clementperon** [comment]
> @liqunfu , would you be able to help?

I will try to propose a new patch that will drop any -mcpu that is set by the toolchain 

But maybe the cleanest way is to detect these functions as "not compilable" with the preferred toolchain flags and drop them. 

Usually if you set a -mcpu in your toolchain you don't need a portable binary with runtime dispatch
