### PR TITLE
Update numpy version from 1.21.0 to 1.21.6 to avoid building it from source

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Update numpy version from 1.21.0 to 1.21.6 to avoid building it from source for python 3.10

**Motivation and Context**
- Why is this change required? What problem does it solve?

To fix the numpy python 3.10 build failures in https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=224016&view=results . The build error I saw was:
"  TypeError: CCompiler_spawn() got an unexpected keyword argument 'env' "

It seems to be a compatibility issue between older numpy versions and newer setuptools versions.  See: https://github.com/pypa/distutils/issues/15 . Most likely it was triggered because I updated the build machines. In the update python 3.10 version was changed from 3.10.5 to 3.10.6.  The python installation has bundled setuptools package which was updated from 50.x to 63.2.0. And the new version somehow doesn't work with numpy 1.21.0 anymore.  

We can avoid the problem by only using prebuilt numpy packages. 

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by mszhanyi — APPROVED** [review]

**Comment by mszhanyi** [comment]
It'd better to add the link of the source
