### ISSUE TITLE
[Build] on Jetson AGX Orin failed

### ISSUE THREAD

**Issue by hillzzz** [microsoft/onnxruntime#26425]
### Describe the issue

Build on Nvidia Jetson AGX Orin CUDA 12.6 failed with:

/home/xxxx/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/log/internal/vlog_config.h(97): error #970-D: the qualifier on this friend declaration is ignored
    friend int log_internal::RegisterAndInitialize(VLogSite* v);
               ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/xxxx/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/log/internal/vlog_config.h(98): error #970-D: the qualifier on this friend declaration is ignored
    friend void log_internal::UpdateVLogSites();
                ^

/home/xxxx/miniconda3/envs/comfyui/include/google/protobuf/parse_context.h(1124): error #2473-D: the "always_inline" attribute is ignored on non-inline functions
  [[nodiscard]] __attribute__((always_inline)) const char*
                               ^

/home/xxxx/miniconda3/envs/comfyui/include/google/protobuf/generated_message_tctable_decl.h(242): error #940-D: missing return statement at end of non-void function "google::protobuf::internal::MakeMapTypeCard"
  }
  ^

4 errors detected in the compilation of "/home/xxxx/onnxruntime/onnxruntime/contrib_ops/cuda/moe/ft_moe/moe_kernel.cu".
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:7620: CMakeFiles/onnxruntime_providers_cuda.dir/home/hillary/onnxruntime/onnxruntime/contrib_ops/cuda/moe/ft_moe/moe_kernel.cu.o] Error 2
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1836: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 2693, in <module>
    sys.exit(main())
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 2594, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.targets)
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 1376, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 148, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/xxxx/onnxruntime/tools/python/util/run.py", line 50, in run
    completed_process = subprocess.run(
  File "/home/xxxx/miniconda3/envs/comfyui/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/hillary/miniconda3/envs/comfyui/bin/cmake', '--build', '/home/xxxx/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.

               ^

### Target platform

Jetson AGX Orin CUDA 12.6 

### Build script

sudo apt install -y --no-install-recommends \
  build-essential software-properties-common libopenblas-dev \
  libpython3.10-dev python3-pip python3-dev python3-setuptools python3-wheel

./build.sh --config Release --update --build --parallel --build_wheel \
--use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu \
--tensorrt_home /usr/lib/aarch64-linux-gnu

### Error / output

/home/xxxx/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/log/internal/vlog_config.h(97): error #970-D: the qualifier on this friend declaration is ignored
    friend int log_internal::RegisterAndInitialize(VLogSite* v);
               ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/xxxx/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/log/internal/vlog_config.h(98): error #970-D: the qualifier on this friend declaration is ignored
    friend void log_internal::UpdateVLogSites();
                ^

/home/xxxx/miniconda3/envs/comfyui/include/google/protobuf/parse_context.h(1124): error #2473-D: the "always_inline" attribute is ignored on non-inline functions
  [[nodiscard]] __attribute__((always_inline)) const char*
                               ^

/home/xxxx/miniconda3/envs/comfyui/include/google/protobuf/generated_message_tctable_decl.h(242): error #940-D: missing return statement at end of non-void function "google::protobuf::internal::MakeMapTypeCard"
  }
  ^

4 errors detected in the compilation of "/home/xxxx/onnxruntime/onnxruntime/contrib_ops/cuda/moe/ft_moe/moe_kernel.cu".
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:7620: CMakeFiles/onnxruntime_providers_cuda.dir/home/hillary/onnxruntime/onnxruntime/contrib_ops/cuda/moe/ft_moe/moe_kernel.cu.o] Error 2
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1836: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 2693, in <module>
    sys.exit(main())
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 2594, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.targets)
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 1376, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/xxxx/onnxruntime/tools/ci_build/build.py", line 148, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/xxxx/onnxruntime/tools/python/util/run.py", line 50, in run
    completed_process = subprocess.run(
  File "/home/xxxx/miniconda3/envs/comfyui/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/hillary/miniconda3/envs/comfyui/bin/cmake', '--build', '/home/xxxx/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.

               ^

### Visual Studio Version

n/a

### GCC / Compiler Version

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04.2)

**Comment by tianleiwu** [comment]
try upgrade gcc?

**Comment by TinyServal** [comment]
gcc 11.4 is not the problem here, it could be related to miniconda or something else in your environment. I am able to successfully build onnxruntime on the same board (identical gcc, python, cuda, tensorrt and ubuntu version), as long as `onnxruntime_BUILD_UNIT_TESTS=OFF` is set.

TensorRT: `./build.sh --config Release --update --build --parallel --build_wheel --use_tensorrt --cuda_home /usr/local/cuda-12.6 --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu --use_cache --skip_tests --cmake_extra_defines 'CMAKE_CUDA_ARCHITECTURES=native' 'onnxruntime_BUILD_UNIT_TESTS=OFF'`

CUDA: `./build.sh --config Release --update --build --parallel --build_wheel --use_cuda --cuda_home /usr/local/cuda-12.6 --cudnn_home /usr/lib/aarch64-linux-gnu --use_cache --skip_tests --cmake_extra_defines 'CMAKE_CUDA_ARCHITECTURES=native' 'onnxruntime_BUILD_UNIT_TESTS=OFF'`
