### PR TITLE
[js/web] Fix conv2dMatmul errors due to #18452

### PR DESCRIPTION
**Pull request by qjia7**
### Description
Currently, all conv2dMatmul with inChannels = 3 and outChannels % 4 = 0 will report compilation errors. Models, which include this kind of shape will be impacted, like mobilenetv2-12,  resnet50 .

The errors is introduced by #18452  https://github.com/microsoft/onnxruntime/pull/18452/files#diff-8b24ea43aa11b1346c0c9e327f9bce6b37a93bd8f2bf8a6392b2b263972b7ea2R200, which accidentally pass `components` to `x`. But `x`'s components is `innerElementSize` not `components `. And when `innerElementSize` is 3, we should use `1`  in current design.

### CODE REVIEW

**Comment by qjia7** [comment]
@fs-eire @guschmue @satyajandhyala Please take a look, thanks!

cc @axinging

**Review by fs-eire — APPROVED** [review]
