### ISSUE TITLE
Project is not fully linked when installing Microsoft.ML.OnnxRuntime.Gpu via nuget-manager

### ISSUE THREAD

**Issue by dnns92** [microsoft/onnxruntime#7922]
**Describe the bug**
I followed this tutorial to get a basic understanding of the onnx runtime on my ubuntu 18.04 machine:
https://github.com/leimao/ONNX-Runtime-Inference. This works as expected.
When switching to windows 10, the run fails when trying to use the gpu. See the minimal example below

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- Working on Ubuntu 18.04
- Not Working on Win10
- ONNX Runtime 1.7.0 (installed via nuget in VS19)
- ONNX Runtime.GPU 1.7.1 & 1.6.0 (installed via nuget in VS19)

**To Reproduce**

consider this minimal example:

```cpp
#include <cuda_provider_factory.h>
#include <onnxruntime_cxx_api.h>
#include <iostream>


int main(int argc, char* argv[])
{

    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);

    // Using CUDA backend
    // https://github.com/microsoft/onnxruntime/blob/rel-1.6.0/include/onnxruntime/core/providers/cuda/cuda_provider_factory.h#L13
    OrtStatus* status =
        OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0);

    std::cout << "fin" << std::endl;

}
```
it fails with 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol OrtSessionOptionsAppendExecutionProvider_CUDA	test-cpp-ort	C:\Users\-\source\repos\test-cpp-ort\test-cpp-ort\test_cuda.obj	1	

and

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	test-cpp-ort	C:\Users\-\source\repos\test-cpp-ort\x64\Release\test-cpp-ort.exe	1	

**Expected behavior**
cout "fin"

**Additional context**
I did not link the project against anything else except installing onnx runtime via nuget.

My cuda:
C:\Users\>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:12:04_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0

**Comment by dnns92** [comment]
I had an incompatible combination of onnx runtime and NVCC. 

see this compatbility matrix to get your combination: https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements
