### ISSUE TITLE
[Build] error C3861: “CreateFileMapping2”: 找不到标识符 

### ISSUE THREAD

**Issue by LuWei6896** [microsoft/onnxruntime#15445]
### Describe the issue

build error

### Urgency

yeah

### Target platform

windows 10 32bit Microsoft Windows [版本 10.0.14393]

### Build script

build.bat --config Release --use_openvino CPU_FP32 --build_shared_lib --cmake_generator "Visual Studio 16 2019" --skip_tests --parallel 3

### Error / output

D:\CV\tool\onnxruntime-4.3\onnxruntime\core\platform\windows\env.cc(403,7): error C3861: “CreateFileMapping2”: 找不到标识符 [D:\CV\tool\onnxruntime-4.3\build\Windows\Release\onnxrunt
ime_common.vcxproj]

### Visual Studio Version

VS2019

### GCC / Compiler Version

C++ compiler version      : 19.29.30148.0

**Comment by snnn** [comment]
Interesting ... I will fix it.

**Comment by snnn** [comment]
The build error was due to #15219 .  Before I made the change, the old code was like:
```
#if WINVER >= _WIN32_WINNT_WIN8
  wil::unique_hfile file_handle{
      CreateFile2(file_path, FILE_READ_ATTRIBUTES, FILE_SHARE_READ, OPEN_EXISTING, NULL)};
#else
  wil::unique_hfile file_handle{
      CreateFileW(file_path, FILE_READ_ATTRIBUTES, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL)};
#endif
```
It's right. CreateFile2 is since Win8. However,  CreateFileMapping2 Windows 10 Build 20348. And your Windows version is 10.0.14393, that's the reason. 

The problem was introduced in #12183 . But we only notice it till now.

**Comment by snnn** [comment]
Wait, it shouldn't happen. It is scoped by 
```
#if NTDDI_VERSION >= NTDDI_WIN10_RS5
```
The if condition should never be true.

**Comment by snnn** [comment]
I will close this issue now. I have used [apivalidator](https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/validating-windows-drivers#apivalidator) to validate our binary with Windows RS4 and RS5's UniversalDDIs.xml. It works fine.  

If you just use your source code, we have defined NTDDI_VERSION  to 0x0A000000. Since it is less than NTDDI_WIN10_RS5, the preprocessor
```c++
#if NTDDI_VERSION >= NTDDI_WIN10_RS5
```
will be false. And the source code will not use CreateFileMapping2.

You can manually modify the NTDDI_VERSION to 0x0A000006, then the final binary will need Windows 10 RS5 or above. I have used the apivalidator.exe to verify that.

**Comment by snnn** [comment]
But I didn't check it for 32bit Windows.

**Comment by LuWei6896** [comment]
ok thanks--发自新浪邮箱客户端
在 4月26日 06:25，Changming Sun ***@***.***> 写道：

I will close this issue now. I have used apivalidator to validate our binary with Windows RS4 and RS5's UniversalDDIs.xml. It works fine.
If you just use your source code, we have defined NTDDI_VERSION  to 0x0A000000. Since it is less than NTDDI_WIN10_RS5, the preprocessor
#if NTDDI_VERSION >= NTDDI_WIN10_RS5
will be false. And the source code will not use CreateFileMapping2.
You can manually modify the NTDDI_VERSION to 0x0A000006, then the final binary will need Windows 10 RS5 or above. I have used the apivalidator.exe to verify that.

&mdash;

**Comment by scarletshroud** [comment]
Thank you! It works!
