### ISSUE TITLE
Build failure when building master branch on Windows

### ISSUE THREAD

**Issue by georgen117** [microsoft/onnxruntime#5297]
**Describe the bug**
When building the code on windows 10 using visual studio 2019 I keep getting the following build failure:

```
C:\onnxruntime\build\Windows\RelWithDebInfo\tml.pb.cc(14,104): error C2653: 'PROTOBUF_INTERNAL_EXPORT_onnx_2fonnx_2dml_2eproto': is not
a class or namespace name [C:\onnxruntime\build\Windows\RelWithDebInfo\onnx_test_data_proto.vcxproj]
```

I used git bisect to try and find the first commit that showed the problem:
git bisect reported 
```
commit 26546f81fe8b99129b1420181ce86b0f3c386283
Author: Changming Sun <chasun@microsoft.com>
Date:   Mon Aug 24 12:40:33 2020 -0700

    Remove the private ONNX protobuf definition file (#4878)
```
as the first commit that showed the problem.

The following build command was being used:
```
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training --build_wheel
```

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: tip of master branch
- Python version: Python 3.8.3
- Visual Studio version (if applicable): Visual Studio Pro version 16.7.4
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
checkout master branch
build using:
```
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training --build_wheel
```

**Expected behavior**
Build without failure

**Comment by tianleiwu** [comment]
@georgen117, if you want to build training, you will need install CUDA etc. Please follow [BUILD.md](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#Training).

For inference, you can remove --enable_training. I used to build cpu-only package like the following:
```
build.bat --config RelWithDebInfo --enable_lto --use_openmp --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --build_wheel
```

**Comment by snnn** [comment]
Did you clean your build folder?

**Comment by georgen117** [comment]
@tianleiwu I know that the build instructions for training want you to install CUDA but you don't actually have to.

I have been working with CPU only training. I have been using it for quit some time and the only thing I have found that didn't work on CPU only training was the Adam Optimizer.

**Comment by georgen117** [comment]
@snnn I tried to clean the build folder but something in Windows must have been holding onto one of the files preventing the full clean of the build folder.

After a full reboot of my system I deleted the build folder and tried again. **It builds successfully.**  A little embarrassed that I created an issue for the problem. Thanks for the help.

closing the issue.
