### ISSUE TITLE
[Build] Must build on Ubuntu 20.04 with gcc 9

### ISSUE THREAD

**Issue by BengtGustafsson** [microsoft/onnxruntime#24168]
### Describe the issue

In 1.21 you start using from_chars for float except for libstdc++ which does not have it. But gcc 9 which is what is available on the still supported ubuntu 20.04 platform. There was also an issue related to lohmann json which forced us to move from 1.21 to main.

It is impossible for us to upgrade beyond Ubuntu 20.04. You should not be this bleeding edge all the time. We have customers around the world and they are slow to update their OSes due to medtec regulatory issues. You can definitely not assume that everyone will upgrade before EOL of a version and should offer a grace period of at least 6 months after something goes out of support, preferrably longer.

I will push a PR that #ifs on the gcc version which we really require to be included in 1.21.1, which is due.... when? The release roadmap is not updated. Our release is due Q2 so I hope it is before end of May at least.

### Urgency

We really need this within May. We don't want to be on our own fork of onnxruntime when we make a release.

### Target platform

linux Ubuntu 20.04

### Build script

Any

### Error / output

In file included from /src/onnxruntime/onnxruntime/test/common/string_utils_test.cc:5:
/src/onnxruntime/include/onnxruntime/core/common/parse_string.h: In instantiation of ‘std::enable_if_t<ParseWithFromChars<T>, bool> onnxruntime::TryParseStringWithClassicLocale(std::string_view, T&) [with T = float; std::enable_if_t<ParseWithFromChars<T>, bool> = bool; std::string_view = std::basic_string_view<char>]’:
/src/onnxruntime/onnxruntime/test/common/string_utils_test.cc:19:3:   required from ‘void onnxruntime::test::{anonymous}::TestSuccessfulParse(const string&, const T&) [with T = float; std::string = std::__cxx11::basic_string<char>]’
/src/onnxruntime/onnxruntime/test/common/string_utils_test.cc:33:34:   required from here
/src/onnxruntime/include/onnxruntime/core/common/parse_string.h:38:41: error: no matching function for call to ‘from_chars(std::basic_string_view<char>::const_pointer, std::basic_string_view<char>::const_pointer, float&)’
   38 |   const auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), parsed_value);
      |                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /src/onnxruntime/include/onnxruntime/core/common/parse_string.h:6,
                 from /src/onnxruntime/onnxruntime/test/common/string_utils_test.cc:5:
/usr/include/c++/9/charconv:600:5: note: candidate: ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int)’
  600 |     from_chars(const char* __first, const char* __last, _Tp& __value,
      |     ^~~~~~~~~~

### GCC / Compiler Version

gcc9

**Comment by fs-eire** [comment]
I think the minimal GCC version requirement is now 11.1:

https://github.com/microsoft/onnxruntime/blob/a8673c6e1d57173ad6c59e6adc494d0852c3887d/cmake/CMakeLists.txt#L259-L261

If you cannot upgrade your GCC version, I think you can checkout an older version of onnxruntime that still working with GCC 9

**Comment by BengtGustafsson** [comment]
Yes, but 1.20 does not allow using the latest TensorRT versions and the version it supports has sporadic crashes. And 1.21 does not allow --usedml and --usetensorrt simultaneously, so we have to go to main which does not build on ubuntu 20.04. I have a patch though, which I will submit as a PR.

**Comment by snnn** [comment]
This issue has been automatically closed because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
