### ISSUE TITLE
Compile error in header onnxruntime_cxx_api.h when update ONNX runtime from 1.5.2 to 1.7.1

### ISSUE THREAD

**Issue by green0765** [microsoft/onnxruntime#7142]
**Describe the bug**
I'm working on updating the ONNX runtime from 1.5.2 of 1.7.1 in our project.
It works well on x64 Linux and Android, but on Windows. It reports strange error in header onnxruntime_cxx_api.h:

onnxruntime_cxx_api.h(257) : error C2059: syntax error: '{'
onnxruntime_cxx_api.h(257) : error C2334: unexpected token(s) preceding '{'; skipping apparent function body
onnxruntime_cxx_api.h(267) : error C2612: trailing '<class-head>' illegal in base/member initializer list
onnxruntime_cxx_api.h(632) : error C1903: unable to recover from previous error(s); stopping compilation

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary 
- ONNX Runtime version: 1.7.1
- Python version:
- Visual Studio version (if applicable): VS2017 with Windows SDK 10.0.16299.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
I comment out all unnecessary code and find only include the header onnxruntime_cxx_api.h get the error:

globle.h:
#ifndef GLOBAL_H
#define GLOBAL_H

#include <onnxruntime_cxx_api.h>

// #define MAX_PATH_LENGTH	2048

// #ifdef _MSC_VER
// #ifdef LIBRARY_EXPORTS
// #    define LIBRARY_API __declspec(dllexport)
// #elif defined(LIBRARY_IMPORTS)
// #    define LIBRARY_API __declspec(dllimport)
// #else
// #define LIBRARY_API
// #endif
// #else
// #define LIBRARY_API
// #endif

//*************************************************************************
// initialize  enviroment...one enviroment per process
// enviroment maintains thread pools and other state info
// LIBRARY_API extern Ort::Env* env;

#endif

source file:
TARGETTYPE=LIBRARY
TARGETNAME=ONNXWRAPPER
RELEASETYPE=LOCAL

C_DEFINES=$(C_DEFINES) /W4 /WX /wd4189 /wd4723 /DORT_API_MANUAL_INIT

INCLUDES = $(INCLUDES); \
           $(OBJECT_ROOT)\onnxruntime\include; \

SOURCES = \
     global.cpp \
     pch.cpp \

TARGETLIBS = \
    $(TARGETLIBS) \
    $(OBJECT_ROOT)\onnxruntime\dll\onnxruntime.dll \

**Expected behavior**
Compile could pass

**Comment by snnn** [comment]
We didn't test it with VS2017. Do you have VS2019, does it fail with the same code? Most likely it's a compiler bug.
