### ISSUE TITLE
Cannot build with CUDA in CMake 3.17.0

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#3355]
**Describe the bug**

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/5203025/77829072-87596700-715a-11ea-87dc-fc4a2dce6dc4.png">

This issue occurred today, with 1.2.0.
I also tried 1.0, which was previously built successfully, and it is also broken, so may not be a regression of ORT itself.

We're using CMake 3.17.0 now, and we noticed there's a hack in Ort: https://github.com/microsoft/onnxruntime/blob/3bdb0b620aaf726a67049886fec44b623dbc85b2/cmake/CMakeLists.txt#L709-L714

With the newly introduced `CMAKE_CUDA_RUNTIME_LIBRARY`, this UB may not work anymore.

Also tested with 3.16.5, works fine.

**Urgency**

Build is blocked by this.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.2.0
- Python version: 3.6
- GCC/Compiler version (if compiling from source): CMake 3.17.0 + Ninja + gcc 8.3.0
- CUDA/cuDNN version: 10.2.89

**Comment by xkszltl** [comment]
On CentOS, even cmake 3.16.5 doesn't work.
Failed with `/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: /usr/local/cuda/targets/x86_64-linux/lib/libcudart_static.a(libcudart_static.a.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'`
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5203025/77861430-72a6cd00-7247-11ea-8754-f192b66bd7c7.png">

**Comment by xkszltl** [comment]
CMake 3.16.4 works for CentOS, there're a lot of CUDA related changes from 3.16.2 to 3.17.0.
I think most related entries are:

> Ninja: Do not use nvcc response files with non-nvcc tools
https://blog.kitware.com/cmake-3-16-5-available-for-download/

> The "CMAKE_CUDA_RUNTIME_LIBRARY" variable and "CUDA_RUNTIME_LIBRARY" target property were introduced to select the CUDA runtime library used when linking targets that use CUDA.
https://blog.kitware.com/cmake-3-17-0-available-for-download/

**Comment by jywu-msft** [comment]
> **Describe the bug**
> 
> <img alt="image" width="1054" src="https://user-images.githubusercontent.com/5203025/77829072-87596700-715a-11ea-87dc-fc4a2dce6dc4.png">
> 
> This issue occurred today, with 1.2.0.
> I also tried 1.0, which was previously built successfully, and it is also broken, so may not be a regression of ORT itself.
> 
> We're using CMake 3.17.0 now, and we noticed there's a hack in Ort:
> 
> https://github.com/microsoft/onnxruntime/blob/3bdb0b620aaf726a67049886fec44b623dbc85b2/cmake/CMakeLists.txt#L709-L714
> 
> With the newly introduced `CMAKE_CUDA_RUNTIME_LIBRARY`, this UB may not work anymore.
> 
> Also tested with 3.16.5, works fine.
> 
> **Urgency**
> 
> Build is blocked by this.
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
> * ONNX Runtime installed from (source or binary): source
> * ONNX Runtime version: 1.2.0
> * Python version: 3.6
> * GCC/Compiler version (if compiling from source): CMake 3.17.0 + Ninja + gcc 8.3.0
> * CUDA/cuDNN version: 10.2.89

yes, there's a problem starting with cmake 3.17 

To make the build succeed, 
replace the following line in onnxruntime/cmake/CMakeLists.txt
string(APPEND CMAKE_CUDA_FLAGS "-cudart shared")
with
set(CMAKE_CUDA_RUNTIME_LIBRARY Shared)
and the CUDA compiler check should succeed.

**Comment by jywu-msft** [comment]
> > **Describe the bug**
> > <img alt="image" width="1054" src="https://user-images.githubusercontent.com/5203025/77829072-87596700-715a-11ea-87dc-fc4a2dce6dc4.png">
> > This issue occurred today, with 1.2.0.
> > I also tried 1.0, which was previously built successfully, and it is also broken, so may not be a regression of ORT itself.
> > We're using CMake 3.17.0 now, and we noticed there's a hack in Ort:
> > https://github.com/microsoft/onnxruntime/blob/3bdb0b620aaf726a67049886fec44b623dbc85b2/cmake/CMakeLists.txt#L709-L714
> > 
> > With the newly introduced `CMAKE_CUDA_RUNTIME_LIBRARY`, this UB may not work anymore.
> > Also tested with 3.16.5, works fine.
> > **Urgency**
> > Build is blocked by this.
> > **System information**
> > 
> > * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
> > * ONNX Runtime installed from (source or binary): source
> > * ONNX Runtime version: 1.2.0
> > * Python version: 3.6
> > * GCC/Compiler version (if compiling from source): CMake 3.17.0 + Ninja + gcc 8.3.0
> > * CUDA/cuDNN version: 10.2.89
> 
> yes, there's a problem starting with cmake 3.17
> 
> To make the build succeed,
> replace the following line in onnxruntime/cmake/CMakeLists.txt
> string(APPEND CMAKE_CUDA_FLAGS "-cudart shared")
> with
> set(CMAKE_CUDA_RUNTIME_LIBRARY Shared)
> and the CUDA compiler check should succeed.

we will try to get this fix checked in.

**Comment by xkszltl** [comment]
@jywu-msft Could you check CMake 3.16.5? That also failed on CentOS 7.
(Well this is not urgent for me since I prefer the latest, but could we problematic for others.)

Also, would be nice if it can be cherry-picked to release versions.

**Comment by jywu-msft** [comment]
> @jywu-msft Could you check CMake 3.16.5? That also failed on CentOS 7.
> (Well this is not urgent for me since I prefer the latest, but could we problematic for others.)
> 
> Also, would be nice if it can be cherry-picked to release versions.

CMAKE_CUDA_RUNTIME_LIBRARY was added in https://gitlab.kitware.com/cmake/cmake/-/commit/1f9321c68399c8cc37a2cb9c78ef45949412bd7b

It doesn't exist in cmake 3.16.5
e.g.
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.16.5/Modules/Compiler/NVIDIA-CUDA.cmake

So it must be a different issue.

**Comment by xkszltl** [comment]
Verified that CentOS 7 + CMake 3.17 + Ort master works.
So that may caused by the same issue.

Maybe there's a gap where Ort's hack doesn't work but the official way hasn't come?
