### PR TITLE
fix: add missing thread header include to TRT-RTX provider

### LINKED ISSUE #25874: [Build] Missing thread header in TRT-RTX provider
https://github.com/microsoft/onnxruntime/blob/16ae99ede405d3d6c59d7cce80c53f5f7055aeed/onnxruntime/core/providers/nv_tensorrt_rtx/nv_execution_provider.cc#L1277

This has been introduced in #25747 and doesn't appear to be satisfied by a respective header import.

I'm not sure how it slipped through testing/CI. Perhaps there's a library that takes care of this that isn't installed automatically.

**GCC Version:** gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
**Target platform:** Linux (x86_64)
**Urgency:** Medium

ONNX built from source (7e3174b0c17673b6e40157389457bba619ab7a84) on nvidia/cuda:12.9.0-cudnn-devel-ubuntu22.04.

### Build Script:
```
python3 tools/ci_build/build.py \
    --build_dir build_gpu \
    --skip_tests \
    --build_shared_lib \
    --build_wheel \
    --parallel 10 \
    --cuda_home /usr/local/cuda \
    --cudnn_home /usr/lib/x86_64-linux-gnu \
    --use_nv_tensorrt_rtx \
    --tensorrt_rtx_home /build/TensorRT-RTX-${TRT_RTX_VERSION} \
    --config Release \
    --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES="100a" \
    CMAKE_CXX_FLAGS="-Wno-error=unused-result" \
    CMAKE_C_FLAGS="-Wno-error=unused-result" \
    --allow_running_as_root
```

### Error:
```
/build/onnxruntime/onnxruntime/core/providers/nv_tensorrt_rtx/nv_execution_provider.cc:1160:39: error: ‘std::thread’ has not been declared
       unsigned int num_threads = std::thread::hardware_concurrency();
```

### PR DESCRIPTION
**Pull request by matfax**
This adds a missing thread header include to satisfy the std::thread access.

### Description
As outlined in #25874, a thread header import seems necessary with the standard set of libs installed and the standard compiler on Ubuntu 22.04.

Fixes #25874

### CODE REVIEW

**Comment by jywu-mysoft** [comment]
@gedoensmax @ishwar-raut1

**Comment by gedoensmax** [comment]
Yes this is correct. Again no CI to catch things like this.

**Comment by gedoensmax** [comment]
This is integrated in #25895 since there were other linux compile issues besides this header.

**Comment by gedoensmax** [comment]
We should be able to close this.
