### ISSUE TITLE
[Build] Error building with ACL EP on aarch64 linux (Raspberry Pi 5)

### ISSUE THREAD

**Issue by andresovela** [microsoft/onnxruntime#23741]
### Describe the issue

I followed the build instructions in [https://onnxruntime.ai/docs/build/inferencing.html](https://onnxruntime.ai/docs/build/inferencing.html) to try to build ONNX Runtime with the ACL Execution Provider, but the build fails.

It seems that the ACL directories are not part of the include directories for some reason.

### Target platform

aarch64 linux (Raspberry Pi 5)

### Build script

```
VERBOSE=1 ./build.sh --config RelWithDebInfo --parallel --compile_no_warning_as_error --skip_submodule_sync --use_acl --acl_home=../arm_compute-v25.02-linux-aarch64-cpu-bin --acl_libs=../arm_compute-v25.02-linux-aarch64-cpu-bin/lib/armv8a-neon-asserts
```

### Error / output

```
[ 43%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/aic/dev/onnxruntime/onnxruntime/core/optimizer/attention_fusion.cc.o
/usr/bin/c++ -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DONLY_C_LOCALE=0 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO=1 -DORT_ENABLE_STREAM -DPLATFORM_POSIX -DUSE_ACL=1 -D_GNU_SOURCE -D__ONNX_NO_DOC_STRINGS -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/utf8_range-src -I/home/aic/dev/onnxruntime/include/onnxruntime -I/home/aic/dev/onnxruntime/include/onnxruntime/core/session -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/pytorch_cpuinfo-src/include -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo -I/home/aic/dev/onnxruntime/onnxruntime -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/abseil_cpp-src -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/safeint-src -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/gsl-src/include -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/date-src/include -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-src -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-build -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/protobuf-src/src -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/flatbuffers-src/include -I/home/aic/dev/onnxruntime/build/Linux/RelWithDebInfo/_deps/mp11-src/include -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -O2 -g -DNDEBUG -fPIC -Wall -Wextra -Wno-deprecated-copy -Wno-nonnull-compare -Wno-maybe-uninitialized -MD -MT CMakeFiles/onnxruntime_optimizer.dir/home/aic/dev/onnxruntime/onnxruntime/core/optimizer/attention_fusion.cc.o -MF CMakeFiles/onnxruntime_optimizer.dir/home/aic/dev/onnxruntime/onnxruntime/core/optimizer/attention_fusion.cc.o.d -o CMakeFiles/onnxruntime_optimizer.dir/home/aic/dev/onnxruntime/onnxruntime/core/optimizer/attention_fusion.cc.o -c /home/aic/dev/onnxruntime/onnxruntime/core/optimizer/attention_fusion.cc
In file included from /home/aic/dev/onnxruntime/onnxruntime/core/providers/acl/acl_common.cc:10:
/home/aic/dev/onnxruntime/onnxruntime/core/providers/acl/acl_common.h:11:10: fatal error: arm_compute/core/experimental/Types.h: No such file or directory
   11 | #include "arm_compute/core/experimental/Types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/onnxruntime_providers_acl.dir/build.make:79: CMakeFiles/onnxruntime_providers_acl.dir/home/aic/dev/onnxruntime/onnxruntime/core/providers/acl/acl_common.cc.o] Error 1
```

**Comment by genehand** [comment]
Ran into the same thing using a `~` for my home dir in `--acl_home` & `--acl_libs`. I changed that to the full path and was able to compile, your relative path might be throwing it off as well. 

You can find the file over in https://github.com/ARM-software/ComputeLibrary/tree/main/arm_compute/core/experimental

**Comment by andresovela** [comment]
Thanks! That seems to have made a difference :) However, the build still fails. These are the two errors that popped up:
```
/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/math/matmul.cc:28:10: fatal error: src/cpu/operators/CpuGemm.h: No such file or directory
   28 | #include "src/cpu/operators/CpuGemm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers_acl.dir/build.make:149: CMakeFiles/onnxruntime_providers_acl.dir/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/math/matmul.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object CMakeFiles/test_execution_provider.dir/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/shared_library/provider_ort_api_init.cc.o
/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/nn/conv.cc:24:10: fatal error: src/cpu/operators/CpuConv2d.h: No such file or directory
   24 | #include "src/cpu/operators/CpuConv2d.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers_acl.dir/build.make:177: CMakeFiles/onnxruntime_providers_acl.dir/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/nn/conv.cc.o] Error 1
```

**Comment by andresovela** [comment]
I just realized that the documentation mentions to build with the ACL v24.07, while I'm on v25.01. I've replaced the ACL with the right version, but it still fails to build, now just with one error:
```
/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/math/matmul.cc:28:10: fatal error: src/cpu/operators/CpuGemm.h: No such file or directory
   28 | #include "src/cpu/operators/CpuGemm.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers_acl.dir/build.make:149: CMakeFiles/onnxruntime_providers_acl.dir/home/andy/dev/projects/onnxruntime/onnxruntime/core/providers/acl/math/matmul.cc.o] Error 1
```
