### ISSUE TITLE
Unable to build on Windows 10 x64 using Visual Studio 16.4 with TensorRT

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#2587]
**Describe the bug**
Trying to build OnnxRuntime from commit 36eb1771bab932043c03544b4b927725f738e9aa for Windows using Visual Studio 2019 (16.4.0) with TensorRT support but this fails.

**Urgency**
We want to use OnnxRuntime from C# and need TensorRT support to get within performance requirements. We would like it before end of year.

**System information**
- Windows 10 Pro 1809
- Source as per commit 36eb1771bab932043c03544b4b927725f738e9aa
- ONNX Runtime version: 1.1.0
- Python version: 3.7
- Visual Studio version (if applicable): 2019 16.4.0
- CUDA/cuDNN version: cuda 10.2.89, cudnn 7.6.5.32, TensorRT 6.0.1.5 as seen below.
```
cuda_10.2.89_win10_network.exe
cudnn-10.2-windows10-x64-v7.6.5.32.zip
TensorRT-6.0.1.5.Windows10.x86_64.cuda-10.1.cudnn7.6.zip
```
- GPU model and memory: Not relevant but 1080 Ti, 2070 Super, 2080 Ti or 1660.

**To Reproduce**
 * Clone onnxruntime git repo at 36eb1771bab932043c03544b4b927725f738e9aa
 * Run following from command prompt with VS2019 vars setup under `onnxruntime`:
```
 ./build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home C:\git\nvidia\cuda --tensorrt_home C:\git\nvidia\TensorRT-6.0.1.5 --use_tensorrt
```
 * Fails with build errors and lots of warnings too.
 * Some errors could be corrected by editing the file `C:\git\oss\onnxruntime\cmake\external\onnx-tensorrt\builtin_op_importers.cpp` to fix 2 compile time issues at:
```
line 812: /*constexpr */auto getMatrixOp = [](const nvinfer1::ITensor& input, bool transpose) { // Comment out constexpr
line 1260: /*constexpr*/ auto getMatrixOp = [](const nvinfer1::ITensor& input) { // Comment out constexpr
```
 * And editing the file `C:\git\oss\onnxruntime\cmake\external\onnx-tensorrt\OnnxAttrs.cpp` at:
```
line 37: //assert(value == bool(value)); // Comment out assert
```
 * This seems to fix compile errors but the build fails. Opening the cmake generated `ALL_BUILD.vcxproj` in Visual Studio and building for debug fails for linker:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB8065	Custom build for item "C:\git\oss\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\da1ed2e4d4eb56aba1863c0aad88ae5b\onnxruntime_generate_def.rule" succeeded, but specified output "c:\git\oss\onnxruntime\build\windows\relwithdebinfo\cmakefiles\onnxruntime_generate_def" has not been created. This may cause incremental build to work incorrectly.	onnxruntime_generate_def	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	231	
Warning	LNK4199	/DELAYLOAD:cudart64_102.dll ignored; no imports found from cudart64_102.dll	onnxruntime (ONNXRuntime\onnxruntime)	C:\git\oss\onnxruntime\build\Windows\RelWithDebInfo\LINK	1	
Error	LNK1218	warning treated as error; no output file generated	onnxruntime (ONNXRuntime\onnxruntime)	C:\git\oss\onnxruntime\build\Windows\RelWithDebInfo\LINK	1	
```

**Expected behavior**
Clean build and the possibility of using OnnxRuntime with TensorRT from C#.

**Comment by snnn** [comment]
BTW,  I just upgrade all our Windows CI CPU machines to VC 16.4, and they work fine.

**Comment by nietras** [comment]
@snnn as far as I understand TensorRT is not build by default. This fails for TensorRT. Could you point to these CI builds?

**Comment by snnn** [comment]
It is. See: https://dev.azure.com/onnxruntime/onnxruntime/_build?definitionId=47&_a=summary

But, you know, it need a GPU machine. All of our GPU machines doesn't have VS 2019 yet. So we can't catch such build failures yet.

**Comment by nietras** [comment]
@snnn thanks for the link! :) Below build seems to match the commit I am building:

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=102386

Noting some differences here:
 * Cuda 10.0 not 10.2
 * Cudnn 7.3.1.20 not 7.6.5.32

I can't find other differences right now, Can't see how those are relevant to the problem though, Sadly the build does not have artefacts that would have been nice.

**Comment by nietras** [comment]
@snnn the errors occur in sub-module code, could this be due to sub-module sync being skipped?

https://github.com/microsoft/onnxruntime/blob/1ee250def883d2630c8ab18019509668dbdda6e3/tools/ci_build/github/azure-pipelines/win-gpu-tensorrt-ci-pipeline.yml#L7

I.e. this contain `--skip_submodule_sync`. So could this be because this uses a different sub-module version?

**Comment by nietras** [comment]
Well the obvious thing is that the CI build still uses VS 15 not 16 as far as I can tell.
```
##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" "c:\agent\_work\7\b\Debug\onnxruntime.sln" /nologo /nr:false /fl /flp:"logfile=c:\agent\_work\7\b\Debug\onnxruntime.sln.log;verbosity=normal" /dl:CentralLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=92648690-20dd-43a2-a91a-fda54c28f8f7|SolutionDir=c:\agent\_work\7\b\Debug"*ForwardingLogger,"C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.151.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /m /p:CudaToolkitDir=C:\local\cuda_10.0.130_win10\ /p:platform="x64" /p:configuration="Debug" /p:VisualStudioVersion="15.0" /m /p:_MSDeployUserAgent="VSTS_f3ad12f2-e480-4533-baf2-635c95467d29_build_47_0"
```
so while machines might have 16 installed it is not used.

**Comment by nietras** [comment]
Realizing that VS 2019 does not work and trying VS 2017 I tried the following from a **Developer Command Prompt for VS 2017**:
```
build.bat --skip_submodule_sync --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib --build_csharp --parallel --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home C:\git\nvidia\cuda --tensorrt_home C:\git\nvidia\TensorRT-6.0.1.5 --use_tensorrt
```
with paths as per my dev machine.  Note that you need to specify cmake path as the cmake bundled with VS 2017 is too old.

This however fails in many places, but specifically `onnxruntime` project fails due to an unnecessary delayload:
```
LINK : warning LNK4199: /DELAYLOAD:cudart64_102.dll ignored; no imports found from cudart64_102.dll [C:\git\oss\onnxruntime\build\Windows\RelWithDebInfo\onn
xruntime.vcxproj]
LINK : error LNK1218: warning treated as error; no output file generated [C:\git\oss\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime.vcxproj]
```
removing this delay load finally meant I got a `onnxruntime.dll`, however there are lots of build errors in test projects e.g. `Microsoft.ML.OnnxRuntime.Tests` fails.

**Comment by nietras** [comment]
Should change the delay load to be for `cudart64_101.dll` instead.

**Comment by nietras** [comment]
The `Microsoft.ML.OnnxRuntime` fails for last copying step:
```
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4582,5): error MSB3030: Could not copy the file "C:\git\oss\onnxruntime\build\Windows\Release\Release\onnxruntime.dll" because it was not found.
```
because it does not user the proper configuration which is `RelWithDebInfo` not `Release`.

This then gives errors in `Microsoft.ML.OnnxRuntime.Tests`:
```
7>InferenceTest.cs(35,30,35,43): error CS0103: The name 'ExecutionMode' does not exist in the current context
7>InferenceTest.cs(35,64,35,77): error CS1061: 'SessionOptions' does not contain a definition for 'ExecutionMode' and no accessible extension method 'ExecutionMode' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(47,21,47,34): error CS1061: 'SessionOptions' does not contain a definition for 'ExecutionMode' and no accessible extension method 'ExecutionMode' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(47,37,47,50): error CS0103: The name 'ExecutionMode' does not exist in the current context
7>InferenceTest.cs(48,30,48,43): error CS0103: The name 'ExecutionMode' does not exist in the current context
7>InferenceTest.cs(48,62,48,75): error CS1061: 'SessionOptions' does not contain a definition for 'ExecutionMode' and no accessible extension method 'ExecutionMode' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(85,21,85,49): error CS1061: 'SessionOptions' does not contain a definition for 'AppendExecutionProvider_CUDA' and no accessible extension method 'AppendExecutionProvider_CUDA' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(94,21,94,53): error CS1061: 'SessionOptions' does not contain a definition for 'AppendExecutionProvider_Tensorrt' and no accessible extension method 'AppendExecutionProvider_Tensorrt' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(173,50,173,63): error CS1061: 'SessionOptions' does not contain a definition for 'ExecutionMode' and no accessible extension method 'ExecutionMode' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(173,66,173,79): error CS0103: The name 'ExecutionMode' does not exist in the current context
7>InferenceTest.cs(539,41,539,71): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(540,37,540,67): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(541,37,541,67): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(542,53,542,83): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(543,41,543,71): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(544,41,544,71): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(545,41,545,71): error CS1061: 'InferenceSession' does not contain a definition for 'OverridableInitializerMetadata' and no accessible extension method 'OverridableInitializerMetadata' accepting a first argument of type 'InferenceSession' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(602,28,602,51): error CS1061: 'SessionOptions' does not contain a definition for 'RegisterCustomOpLibrary' and no accessible extension method 'RegisterCustomOpLibrary' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(676,63,676,81): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(677,63,677,81): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(678,65,678,83): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(681,37,681,55): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(683,37,683,55): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(685,38,685,56): error CS1061: 'NodeMetadata' does not contain a definition for 'SymbolicDimensions' and no accessible extension method 'SymbolicDimensions' accepting a first argument of type 'NodeMetadata' could be found (are you missing a using directive or an assembly reference?)
7>InferenceTest.cs(1399,41,1399,74): error CS0117: 'SessionOptions' does not contain a definition for 'MakeSessionOptionWithCudaProvider'
7>Done building project "Microsoft.ML.OnnxRuntime.Tests.csproj" -- FAILED.
```
I do not know why this does not work OOB, what am I doing wrong?

**Comment by nietras** [comment]
@snnn any status on this? How can I compile with VS 16.4 or later? As I showed I could not find any CI builds showing how this is done or that it works?

**Comment by snnn** [comment]
All of our CI build have been migrated to VC 16.4 except tensorrt.

**Comment by nietras** [comment]
@snnn has the issue been fixed? Is it possible to build with TensorRT on VS2019 now?

**Comment by snnn** [comment]
@stevenlix Could you help him?

**Comment by nietras** [comment]
@snnn @stevenlix I finally managed to build this after updating to 1d79926d273d01817ce93f001f36f417ab05f8a0 with the following build parameters:
```
build.bat  --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib --build_csharp --parallel --use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home C:\git\nvidia\cuda --use_tensorrt --tensorrt_home C:\git\nvidia\TensorRT-7.0.0.11 --use_dnnl --cmake_generator "Visual Studio 16 2019" --skip_tests
```
Run from a **Developer Command Prompt for VS 2019**. I am, therefore, closing the issue.

**Comment by solarflarefx** [comment]
@nietras How much of an acceleration boost did TensorRT give you using the C# API?  I am wondering how much the boost would compare running through ONNX Runtime C# API versus running a TensorRT engine in C++.

Also, did your build problems get fixed with the latest version of ONNX Runtime?  What did you use as a guide for building on Windows 10 x64 and VS 2019?  Aside from the problems you listed on here, were there any other major hurdles?  

And finally I wanted to clarify that you ultimately ran your TensorRT optimized solution in C# and not C++.

Thanks in advance.
