### ISSUE TITLE
onnxruntime in c++ to predict output using .onnx model

### ISSUE THREAD

**Issue by Debottam** [microsoft/onnxruntime#1765]
Hi,
I have built onnxRuntime from source where I can use a .onnx model to predict output  in python. I would like to do same prediction in C++, I need guidance on that how to proceed (e.g loading the .onnx model, printing outputs etc.) I found 
#include "onnx/onnx.pb.h"
#include <fstream>
#include <iostream>

int main(void) {
        onnx::ModelProto model;
        std::ifstream in("mnist.onnx", std::ios_base::binary);
        model.ParseFromIstream(&in);
        in.close();
        std::cout<<model.graph().input().size()<<"\n";
}
but I am using onnxRuntime I don't see onnx/onnx.pb.h there. Please help.
Thanks,
Debottam

**Comment by bitnick10** [comment]
Use [protoc](https://developers.google.com/protocol-buffers/docs/downloads) compile [onnx.proto](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto) can get onnx.pb.h

**Comment by Debottam** [comment]
Hi @bitnick10,
Thanks for the reply but do I have onnx.proto under onnx runtime? I dont see it.
Thanks,
Debottam.

**Comment by bitnick10** [comment]
I don't see onnx.proto ,either.You may need download it from onnx project.
onnxruntime follows the [onnx](https://github.com/onnx/onnx) rules,I nerver compiled success from source.For more infomation, you may want to wait the team's member answer.

**Comment by nlyf** [comment]
Hi, @Debottam !
I'am not shure, but I guess you can try this [example](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md). 
Unfortenatly, I'm getting error 
```code
 error: ‘OrtGetAllocatorWithDefaultOptions’ was not declared in this scope
   CHECK_STATUS(OrtGetAllocatorWithDefaultOptions(&allocator));
```
when trying to compile with ` g++ -Lonnxruntime-linux-x64-0.5.0/lib -o api_sample api_sample.cpp -I onnxruntime-linux-x64-0.5.0/include -lonnxruntime`. 
maybe it helps

**Comment by nlyf** [comment]
As i can see, my problem was related to [renaming](https://github.com/microsoft/onnxruntime/pull/1615/files):
`OrtCreateDefaultAllocator->OrtGetAllocatorWithDefaultOptions`

**Comment by Debottam** [comment]
Hi @nlyf ,

Thanks it was indeed useful I still have a bug
my complilation command becomes
**g++ -L /home/debo/onnxruntime/core/mlas/lib -o api_sample1 C_Api_Sample1.cpp -I /home/debo/onnxruntime/include -lonnxruntime -std=c++14**

C_Api_Sample1.cpp: In function ‘int main(int, char**)’:
C_Api_Sample1.cpp:35:50: warning: ignoring return value of ‘OrtStatus* OrtSetSessionThreadPoolSize(OrtSessionOptions*, int)’, declared with attribute warn_unused_result [-Wunused-result]
   OrtSetSessionThreadPoolSize(session_options, 1);
                                                  ^
C_Api_Sample1.cpp:38:73: warning: ignoring return value of ‘OrtStatus* OrtSetSessionGraphOptimizationLevel(OrtSessionOptions*, GraphOptimizationLevel)’, declared with attribute warn_unused_result [-Wunused-result]
   OrtSetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_BASIC);
                                                                         ^
C_Api_Sample1.cpp:91:78: warning: ignoring return value of ‘OrtStatus* OrtGetDimensions(const OrtTensorTypeAndShapeInfo*, int64_t*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     OrtGetDimensions(tensor_info, (int64_t*)input_node_dims.data(), num_dims);
                                                                              ^
**/usr/bin/ld: cannot find -lonnxruntime**
collect2: error: ld returned 1 exit status
also I don't see any .so file inside any lib directory.
need help.

**Comment by nlyf** [comment]
@Debottam, have you downloaded libs from release page?

**Comment by Debottam** [comment]
@nlyf,
I have built onnxruntime from source git clone --recursive https://github.com/Microsoft/onnxruntime
Do I have to download libs separately? If so could provide me tve link to do this?
Thanks,
Debottam

**Comment by Debottam** [comment]
Hi @nlyf 

The current lib file I have is what you can see in https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/mlas/lib/ but it doesn't have any *.so file, do I need to find some other directory??

**Comment by Debottam** [comment]
Hi @nlyf,
I would like to mention how I am building onnxruntime, I want you to correct if I am missing anything here for that may be its not generating ant onnxruntime.so file
So I am following this link for building onnxruntime https://github.com/microsoft/onnxruntime/blob/master/BUILD.md
step1:
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
step2:
Install cmake-3.13 or better from https://cmake.org/download/.
step3:
./build.sh --config RelWithDebInfo --build_shared_lib --parallel

btw using the onnxrutime built above I am able to run it in python but having trouble in C++. Need help

Thanks in advance,
Debottam.

**Comment by nlyf** [comment]
@Debottam,
I do not have experience building from source. I just downloaded libs from here https://github.com/microsoft/onnxruntime/releases

**Comment by faxu** [comment]
@debottam did you take a look at these examples? https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx

**Comment by Debottam** [comment]
Hi @faxu 
The thing is I have linux system there fore I would like to build it in linux the example is in visual C if its possible to run the same example in linux that would be great.

**Comment by Debottam** [comment]
Hi @nlyf ,
I have checked out onnxruntime-linux-x86-0.5.0 package instead of building my own and inside onnxruntime-linux-x86-0.5.0 directory I tried to run my code
>> g++ -L/home/debo/onnxruntime-linux-x86-0.5.0/lib -lonnxruntime -o api_sample1 C_Api_Sample1.cpp -I ./include -std=c++14

but I got the error 
/usr/bin/ld: skipping incompatible /home/debo/onnxruntime-linux-x86-0.5.0/lib/libonnxruntime.so when searching for -lonnxruntime
/usr/bin/ld: cannot find -lonnxruntime
collect2: error: ld returned 1 exit status

Then I checked 
~/onnxruntime-linux-x86-0.5.0$ ls lib
libonnxruntime.so  libonnxruntime.so.0.5.0
so I tried
g++ -L/home/debo/onnxruntime-linux-x86-0.5.0/lib **-llibonnxruntime** -o api_sample1 C_Api_Sample1.cpp -I ./include -std=c++14 (instead of -lonnxruntime)
but got error
/usr/bin/ld: cannot find -llibonnxruntime
collect2: error: ld returned 1 exit status

any idea?
Thanks,
Debottam.

**Comment by nlyf** [comment]
@Debottam 
As you can see from errors: lib is incompatible. Do you have x86 OS? 
As I've said [before](https://github.com/microsoft/onnxruntime/issues/1765#issuecomment-528724276) try building the same way

**Comment by Debottam** [comment]
Hi @nlyf,
yes I do have x86 os
debo@supercomputer:~$ uname -m
x86_64
Thanks,
Debottam

**Comment by Debottam** [comment]
Hi @nlyf 
I have uploaded the test I am running here https://github.com/Debottam/squeezeNetExample/tree/master/onnxruntime-linux-x86-0.5.0 
I am running the example (squeezeNet) you suggested and I am using c_api which resolved the error: ‘OrtGetAllocatorWithDefaultOptions’ was not declared in this scope
   CHECK_STATUS(OrtGetAllocatorWithDefaultOptions(&allocator));
The command I am using 
 g++ -L ./lib -o api_sample C_Api_Sample.cpp -I ./include -lonnxruntime -std=c++14

and output I am getting
/usr/bin/ld: skipping incompatible ./lib/libonnxruntime.so when searching for -lonnxruntime
/usr/bin/ld: cannot find -lonnxruntime
collect2: error: ld returned 1 exit status

Thanks,
Debo.

**Comment by Debottam** [comment]
Hi @nlyf , @faxu  ,

I got some success in building from onnxruntime from the source (please let me know if I should make a separate issue for the details.
As I mentioned
I was doing following steps to build onnxruntime from source
step1:
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
step2:
Install cmake-3.13 or better from https://cmake.org/download/.
step3:
./build.sh --config RelWithDebInfo --build_shared_lib --parallel

This onnx runtime runs in python successfully (I have written a code here https://github.com/UTA-HEP-Computing/TensorFlowToOnnx/blob/master/tfToOnnx.ipynb) 

but one thing is this seems not for x86_64 
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L776

but I went ahead and compile my C++ code which is the squeezenet example (https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp)

>> g++ -L /home/debo/onnxruntime/build/Linux/RelWithDebInfo/ -o Capi_sample C_Api_Sample.cpp -I ./include -lonnxruntime -std=c++14 

(** this time I found the right address of .so file)

it creates the executable and when I run it 
>> ./Capi_sample
it complains
./Capi_sample: error while loading shared libraries: libonnxruntime.so.0.5.0: cannot open shared object file: No such file or directory

*******Another trial build from source with --x86 flag on *******
according to https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py if I build onnxruntime with x86 flag it will build specific to x86, so I did following

>> ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --x86

but I get following errors
....
CMakeFiles/Makefile2:490: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
....
[ 21%] Linking CXX static library libprotobuf.a
[ 21%] Built target libprotobuf
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/debo/onnxruntime/tools/ci_build/build.py", line 978, in <module>
    sys.exit(main())
  File "/home/debo/onnxruntime/tools/ci_build/build.py", line 927, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/debo/onnxruntime/tools/ci_build/build.py", line 446, in build_targets
    run_subprocess(cmd_args)
  File "/home/debo/onnxruntime/tools/ci_build/build.py", line 192, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/debo/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j48']' returned non-zero exit status 2 
....
etc.

Need suggestions.
Thanks,
Debottam.

**Comment by nlyf** [comment]
@Debottam, pay more attention to my comments. https://github.com/microsoft/onnxruntime/issues/1765#issuecomment-528724276
