### ISSUE TITLE
DEBUG_NODE_INPUTS_OUTPUTS build broken

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#2345]
**Describe the bug**

```bash
./build.sh --config Debug --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=1 --build_shared_lib --build_wheel --parallel

```

> /home/ehazar/repos/onnxruntime/onnxruntime/core/framework/utils.cc:608:86: error: unused parameter ‘session_state’ [-Werror=unused-parameter]                                                                                                                                    void DumpNodeOutputs(OpKernelContext& context, const Node& node, const SessionState& session_state) {

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.0.0
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 5.4

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

Patch:

```C++
diff --git a/onnxruntime/core/framework/utils.cc b/onnxruntime/core/framework/utils.cc
index 545559d5b..429804bce 100644
--- a/onnxruntime/core/framework/utils.cc
+++ b/onnxruntime/core/framework/utils.cc
@@ -605,7 +605,7 @@ void DumpNodeInputs(const OpKernelContext& context, const Node& node) {
   }
 }

-void DumpNodeOutputs(OpKernelContext& context, const Node& node, const SessionState& session_state) {
+void DumpNodeOutputs(OpKernelContext& context, const Node& node, const SessionState& /*session_state*/) {
   std::cout << "-----------\n";
   const auto& output_defs = node.OutputDefs();

```

**Comment by jywu-msft** [comment]
Thanks for reporting the issue.
It's caused by https://github.com/microsoft/onnxruntime/pull/2243
@tianleiwu , FYI
