### PR TITLE
Fix iconv link issue

### LINKED ISSUE #15560: [Build] Build failed due to undefined reference to libiconv
### Describe the issue

Hi,
I am build onnxruntime using the command `./build.sh --config Release --build_shared_lib --parallel`. 
The machine is running Ubuntu 22.04 and also has a GPU GTX1080Ti (Cuda).
During the build I encountered an error regarding an undefined reference to libiconv. 
Below is the output:

```
apper<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const*, onnxruntime::OpKernelContext*, onnxruntime::string_normalizer::Locale const&, onnxruntime::string_normalizer::Utf8Converter&, unsigned long, unsigned long, onnxruntime::StringNormalizer::CaseAction)':
string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x417): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x490): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x4cb): undefined reference to `libiconv_close'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x64f): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x6d9): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x710): undefined reference to `libiconv_close'
/usr/bin/ld: libonnxruntime_providers.a(string_normalizer.cc.o): in function `onnxruntime::StringNormalizer::Compute(onnxruntime::OpKernelContext*) const':
string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x81f): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x8a7): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x8df): undefined reference to `libiconv_close'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xda4): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xe39): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xe6d): undefined reference to `libiconv_close'
/usr/bin/ld: libonnxruntime_providers.a(string_normalizer.cc.o): in function `onnxruntime::StringNormalizer::StringNormalizer(onnxruntime::OpKernelInfo const&)':
string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x92b): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x9b3): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x9eb): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/onnxruntime_test_all.dir/build.make:4656: onnxruntime_test_all] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2136: CMakeFiles/onnxruntime_test_all.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):

```

A similar issue was reported in 2020, issue number [4232](https://github.com/microsoft/onnxruntime/issues/4234). However, there was no satisfactory solution there.

I tried installing libiconv using directions [here](https://geeksww.com/tutorials/libraries/libiconv/installation/installing_libiconv_on_ubuntu_linux.php). However, it did not work.

Another link [here](https://askubuntu.com/questions/898826/why-is-there-no-libiconv-package-in-ubuntu) suggests that libiconv is included in the libc6 package as a GNU standard C library. I don't know how to use this info.

If anyone can provide concrete steps to fix this issue or any help, it would be great.
Thanks.

### Urgency

It's blocking my research project progress. Strict deadlines.

### Target platform

Ubuntu 22.04

### Build script

https://github.com/microsoft/onnxruntime/blob/main/build.sh

### Error / output

apper<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const*, onnxruntime::OpKernelContext*, onnxruntime::string_normalizer::Locale const&, onnxruntime::string_normalizer::Utf8Converter&, unsigned long, unsigned long, onnxruntime::StringNormalizer::CaseAction)':
string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x417): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x490): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x4cb): undefined reference to `libiconv_close'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x64f): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x6d9): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE[_ZN11onnxruntime17string_normalizer14CopyCaseActionIPKSt17reference_wrapperIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_6common6StatusET_SF_PNS_15OpKernelContextERKNS0_6LocaleERNS0_13Utf8ConverterEmmNS_16StringNormalizer10CaseActionE]+0x710): undefined reference to `libiconv_close'
/usr/bin/ld: libonnxruntime_providers.a(string_normalizer.cc.o): in function `onnxruntime::StringNormalizer::Compute(onnxruntime::OpKernelContext*) const':
string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x81f): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x8a7): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0x8df): undefined reference to `libiconv_close'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xda4): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xe39): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZNK11onnxruntime16StringNormalizer7ComputeEPNS_15OpKernelContextE+0xe6d): undefined reference to `libiconv_close'
/usr/bin/ld: libonnxruntime_providers.a(string_normalizer.cc.o): in function `onnxruntime::StringNormalizer::StringNormalizer(onnxruntime::OpKernelInfo const&)':
string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x92b): undefined reference to `libiconv_open'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x9b3): undefined reference to `libiconv'
/usr/bin/ld: string_normalizer.cc:(.text._ZN11onnxruntime16StringNormalizerC2ERKNS_12OpKernelInfoE+0x9eb): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/onnxruntime_test_all.dir/build.make:4656: onnxruntime_test_all] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2136: CMakeFiles/onnxruntime_test_all.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):

### Visual Studio Version

_No response_

### GCC / Compiler Version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### PR DESCRIPTION
**Pull request by snnn**
### Description
Fix iconv link issue. The library is used in string_normalizer.cc. 

### Motivation and Context
Resolved #15560

### CODE REVIEW

**Review by jchen351 — APPROVED** [review]
Works on M2 MacOS 13.3

**Comment by snnn** [comment]
Do not merge yet. It needs more discussion.

**Review by jchen351 — APPROVED** [review]
