### ISSUE TITLE
[Training] Cannot generate ONNX graph for training

### ISSUE THREAD

**Issue by srijanie03** [microsoft/onnxruntime#22188]
### Describe the issue

I am trying to generate a training graph by specifying the model path directly. It works correctly on CUDA (12.4) but when I run the same  on Windows, I get an error as this:

`AttributeError: 'str' object has no attribute 'graph'`.
When I print the forward graph I can clearly see the attribute 'graph' in it. 

It does not seem to be model specific as this issue occurs for every graph I try by specifying the model path. Doing `onnx.load(onnx_model_path)` works but not for a model that is bigger than 2GB.

Attaching the forward onnx graph for reference.
![lora_2layer onnx](https://github.com/user-attachments/assets/de19fdd6-2579-4cd4-a288-310154e6c437)

### To reproduce

`#Backward graph
artifacts.generate_artifacts(
    "lora_2layer.onnx",
    optimizer=artifacts.OptimType.AdamW,
    loss=artifacts.LossType.CrossEntropyLoss,
    requires_grad=requires_grad,
    frozen_params=frozen_params,
    artifact_directory="lora_2layer",
    additional_output_names=["output"])`

### Urgency

Very urgent

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.19.0

### PyTorch Version

2.4.0

### Execution Provider

Default CPU

### Execution Provider Library Version

CUDA 12.4
