### ISSUE TITLE
Not compatible with latest Eigen preinstalled in system

### ISSUE THREAD

**Issue by Debottam** [microsoft/onnxruntime#2812]
Hi,
I have latest eigen (3.3.7) installed in our framework. While building onnxruntime from source if we use this pre installed eigen -Donnxruntime_USE_PREINSTALLED_EIGEN:BOOL=ON , we get error 
onnxruntime/include/onnxruntime/core/platform/threadpool.h:64:10: error: 'ThreadPool' in namespace 'Eigen' does not name a type Eigen::ThreadPool .. The thing is we don't want two different version of eigen; could you point us to the eigen release used by onnxruntime. Our system is centos7

Thanks,
Debo.

**Comment by snnn** [comment]
It's hard to support multiple eigen versions at the same time. Would you please turn onnxruntime_USE_PREINSTALLED_EIGEN off? BTW, I don't see the value of enabling it.

**Comment by Debottam** [comment]
Hi @snnn ,
Thanks for replying. So you can see this particular variable here https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L65 we tried build the onnxruntime by turning it ON, because we have programs which runs in our framework with our eigen package (3.3.7) we are just worried if onnxruntime introduces a different version of eigen then will that create a mismatch? Therefore we wanted to know if the eigen used by onnxruntime is available in any release so we update our preinstalled eigen to onnxruntime eigen so that's how we will have a uniform version of eigen.

Thanks,
Debo.

**Comment by snnn** [comment]
> will that create a mismatch? 
No, if at build time, onnxruntime can't see another eigen. It can cause confusion only if there are two different eigen in onnxruntime's INCLUDE path.

**Comment by faxu** [comment]
The versions of dependencies used by ORT should be up to date here: https://github.com/microsoft/onnxruntime/blob/master/cgmanifest.json

From @snnn's latest response it seems like this should not be an issue regardless of whether that flag is on or off, but may be recommended to turn off.

**Comment by Debottam** [comment]
Hi @snnn and @faxu,

Coming back to this 
**1st: Need of latest version of eigen:**
We use eigen objects extensively in our codes. We are using the latest Eigen-3.3.7. There is a lot of shift from the version you are using in onnxruntime to the latest Eigen-3.3.7. Many functions have become obsolete/replaced in Eigen-3.3.7. In our computing framework if we have two different versions of Eigen, during runtime we cannot make provision for codes involving onnxruntime to use a different version of eigen. So during runtime it will choose any one of the two eigen versions and will fail those codes which are not compatible to that particular eigen version.

2nd: Simple patching won't fix:
We tried using some patch file to make onnxruntime compatible to latest Eigen 3.3.7 so that we can keep only one version of eigen package but the differnces are way deeper, for example

```
/srv/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::BitShift<T>::Compute(onnxruntime::OpKernelContext*) const [with T = long unsigned int]':
/srv/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.h:276:10:   required from here
/srv/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:539:11: error: 'begin' was not declared in this scope
           for (const auto& input : input1.array()) {
           ^~~
```
So you can see there are changes in looping methods in current Eigen than the older; I can give more details in this. 

So above two conclusive points made us wonder if onnxruntime is planning to upgrade its Eigen to the latest version in the near future? or provide any solutions to the above issues?

Thanks,
Debo.

**Comment by snnn** [comment]
> So during runtime it will choose any one of the two eigen versions.

No, it won't.

**Comment by Debottam** [comment]
Hi @snnn 
By "it" I meant our atlas software framework (athena) ; if there are different codes relying on two different versions of eigen (which is true for our framework) then during runtime our framework will pick up any one of the two eigen versions which will detrimental to the codes which doesn't depend on that particular version. I hope "it" is clear here.
For Prebuilt Version: we cannot use it since we provide our framework to users with different OS (MAC, Ubuntu, centos, etc) so its is only ideal to use a build fro source. I hope what I am pointing makes sense. 
Please let us know if you have solution based on above points.
Thanks,
Debo.

**Comment by snnn** [comment]
> will pick up any one of the two eigen versions 
No. It will pick up both of them.

**Comment by krasznaa** [comment]
:confused: There seems to be a **lot** of confusion around what our issue is. So I created the following demonstration, which will hopefully clarify why we **insist** on using the same Eigen version in all the libraries that we use:

https://github.com/krasznaa/EigenVersionProblem

Please have a look at that code.
  - It has two different versions of an `eigen.h` header: [oldEigen/eigen.h](https://github.com/krasznaa/EigenVersionProblem/blob/master/oldEigen/eigen.h) and [newEigen/eigen.h](https://github.com/krasznaa/EigenVersionProblem/blob/master/newEigen/eigen.h).
    * As in Eigen itself, that is a header-only piece of code. Both headers provide a function called `Eigen::printSomething()`.
  - The code builds two shared libraries out of [oldLibrary/oldLibrary.cxx](https://github.com/krasznaa/EigenVersionProblem/blob/master/oldLibrary/oldLibrary.cxx) and [newLibrary/newLibrary.cxx](https://github.com/krasznaa/EigenVersionProblem/blob/master/newLibrary/newLibrary.cxx).
    * The functions in both just execute `Eigen::printSomething()`, after including `<eigen.h>`.
  - Then I've set up 3 test executables. One that only uses the "old shared library", one that uses the "new shared library", and one that uses both.
    * The latter one I build two different times. Changing the older of the two shared libraries given to the linker in the two cases.

As the [README](https://github.com/krasznaa/EigenVersionProblem/blob/master/README.md) file says as well, this code produces the following output after compilation:

```sh
[bash][thor]:install > ./bin/testNew
New printout
[bash][thor]:install > ./bin/testOld
Old printout
[bash][thor]:install > ./bin/testBoth1
Old printout
Old printout
[bash][thor]:install > ./bin/testBoth2
New printout
New printout
[bash][thor]:install >
```

Since both header-only "Eigen versions" declare the same function, at runtime the machine assumes that the function called `Eigen::printSomething()`, which is present in both `libOldLibrary.so` and `libNewLibrary.so`, is the same. So it only loads the "first one", and ignores the second one. And boom goes the dynamite, we get this very undesirable output.

**This** is why we can't afford to have two different Eigen versions be used in our build. Because we want to use `libonnxruntime.so` together with hundreds of other shared libraries, which will be using the latest version of Eigen. There is absolutely no way around it. Either ONNXRuntime can use the same version of Eigen, or we won't be able to use it. :frowning:

**Comment by snnn** [comment]
https://gcc.gnu.org/wiki/Visibility

**Comment by krasznaa** [comment]
Seriously? A single line? :confused: 

Then let me put into a single line: Our code doesn't allow for symbol hiding. (Template symbol resolution is **very** fragile on Linux when symbols are being hidden.)

**Comment by snnn** [comment]
Please pardon me, do you agree that it's not a problem on Windows platform, so we can focus our discussion on Linux? Do you have other platforms needed to support?

**Comment by krasznaa** [comment]
As Debo must've said in the past, we are only focusing on [CentOS 7](http://linux.web.cern.ch/linux/centos7/) with [GCC 8](https://gcc.gnu.org/gcc-8/) at the moment. (Unfortunately the [ATLAS offline software](https://gitlab.cern.ch/atlas/athena) does a number of things that are quite incompatible with Windows. But I guess I don't have to defend that if one wants to run some application on hundreds of thousands of CPU cores at once, one does that with some flavour of Linux...)

What made me wonder though: Does `libonnxruntime.so` only expose the symbols that are appearing in its "public header"? I was trying to check this with some `readelf` commands, but I have to admit, my expertise with that tool is pretty basic... :frowning:

Since you could in fact make the argument that as long as your library is only exposing the symbols for the functions/classes that we should directly interact with, things **should** work on our end. Even though, as I said, we've seen some weird things in our code in the past when we tried hiding symbols in shared libraries.

**Comment by pranavsharma** [comment]
@krasznaa you can run nm -C -D libonnxruntime.so to see which symbols are exposed by onnxruntime. When we run our Linux build, we generate a file called onnxruntime.lds (linker version script) that defines the symbols we expose. You can read more about this [here](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_25.html). The contents of this file (for 1.0 release as an example) is as follows:

```
VERS_1.0.0 {
 global:
  OrtGetApiBase;
  OrtSessionOptionsAppendExecutionProvider_CPU;
 local:
    *;
};
```

Hence things should work on your end even with a different Eigen version. Have you tried it?

**Comment by faxu** [comment]
@Debottam as we discussed, i believe this issue is now resolved for you? can you please confirm and close the issue if so? Let us know if you have further issues. Thanks!

**Comment by Debottam** [comment]
Hi @faxu 
Thanks, sure since this ticket is specific to Eigen issue and that has been resolved, so please go ahead and close this  issue.
