### ISSUE TITLE
Unable to compile on Linux with CUDA

### ISSUE THREAD

**Issue by mfenton0** [microsoft/onnxruntime#6749]
**Describe the bug**
I am unable to compile onnxruntime with cuda using my docker image. When I compile on my Ubuntu20.04 machine, things work fine - as well as when I compile without cuda. However, in my centos7 docker image, I get errors:

/home/mfenton/ONNX/GPUComp/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.h:81:7: error: 'GetDeviceId' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  int GetDeviceId() const { return device_id_; }

/home/mfenton/ONNX/GPUComp/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:247:25: error: private field 'prop_' is not used [-Werror,-Wunused-private-field]
  const cudaDeviceProp& prop_;

Since the same code compiles ok on my local machine, I'm confused as to why this would be. I tried to work around it by adding "#pragma GCC diagnostic ignored "-Wxyz" in the relevant headers but I Just get new errors further down. 

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos7 docker image
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: using branch v1.5.1
- Python version: 3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.2 / 8.0
- GPU model and memory: Geforce RTX 3080

**To Reproduce**
I'm not sure if everything needed is public, but hopefully this works:
Pull the docker image: gitlab-registry.cern.ch/akraszna/atlas-gpu-devel-env/fullcuda:centos7-1-3-1
checkout onnxruntime: git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
./build.sh --use_cuda --cuda_home=/usr/local/bin/ --cudnn_home=/usr/local/bin/ --config RelWithDebInfo --build_shared_lib

**Expected behavior**
Successful compilation of onnxruntime including cuda

**Screenshots**
<>

**Additional context**
I'm trying to compile onnxruntime with cuda support inside an existing development environment. This is the first step just to get it to compile in a docker image containing that environment.

**Comment by yuslepukhin** [comment]
We build it using this  [docker](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_gpu)
