### ISSUE TITLE
[Build] Unable to use CoreML: This binary was not compiled with CoreML support.

### ISSUE THREAD

**Issue by gauravphoenix** [microsoft/onnxruntime#16230]
### Describe the issue

Hello, I am using the dependency - 

```
    <dependency>
      <groupId>com.microsoft.onnxruntime</groupId>
      <artifactId>onnxruntime</artifactId>
      <version>1.15.0</version>
    </dependency>

```
and with the following code- 
``` java
  var env = OrtEnvironment.getEnvironment();
  var sessionOptions = new OrtSession.SessionOptions();
  sessionOptions.addCoreML();
  var session = env.createSession("model.onnx", sessionOptions);
```

I get error 

```Error code - ORT_INVALID_ARGUMENT - message: This binary was not compiled with CoreML support.```

So I tried building the package myself like this- 
`./build.sh --update --build --build_java --config Release --parallel`

but that gives an error 

```
CMake Error at /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  onnxruntime_java.cmake:11 (find_package)
  CMakeLists.txt:1631 (include)
  ```

`java -version` output- 

```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Homebrew (build 17.0.7+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.7+0, mixed mode, sharing)
```

Any suggestion on how to go about fixing it? I would rather use pre-built binary than spend time resolving build issues 

### Target platform

macOS

### Build script

`./build.sh --update --build --build_java --config Release --parallel`

### Error / output

`  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  onnxruntime_java.cmake:11 (find_package)
  CMakeLists.txt:1631 (include)`

### GCC / Compiler Version

arm64-apple-darwin22.4.0

**Comment by Craigacp** [comment]
You need to compile from source to get CoreML support, I think the selector on onnxruntime.ai is misleading here by saying it's compiled in the binary on Maven Central (@faxu should that be updated?).

Cmake pulls in the JNI support by looking for the `$JAVA_HOME` environment variable and reading things out of that. The default location for OpenJDK in Homebrew is `/opt/homebrew/opt/openjdk/`, so try setting it to that.

Running `./build.sh --update --build --build_java --config Release --parallel --use_coreml` on an M1 laptop with macOS 13.4 on a clean checkout of `v1.15.0` still gives me an error when adding CoreML and it looks like it's because the name of the native flag changed. If you modify line 603 of [this file](https://github.com/microsoft/onnxruntime/blob/main/java/src/main/native/ai_onnxruntime_OrtSession_SessionOptions.c#L603) to say `#ifdef USE_COREML`, note there is only one underscore, then you should get a CoreML compatible jar file. I'll put in a PR with the fix.

**Comment by gauravphoenix** [comment]
Thanks so much for the detailed response, seems like `JAVA_HOME` and `cmake` are acting naughty on my machine. 
if I do `ls $JAVA_HOME/include` I see 
```
classfile_constants.h jawt.h                jawt_md.h             jdwpTransport.h       jni.h                 jni_md.h              jvmti.h               jvmticmlr.h
```

but when I run `./build.sh --update --build --build_java --config Release --parallel --use_coreml` I still get this error- 

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.26/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  onnxruntime_java.cmake:16 (find_package)
  CMakeLists.txt:1631 (include)
```
so it seems like `JAVA_HOME` is not being honored by `cmake` or it is somehow not able to read it. There is some reference to the problem [here](https://stackoverflow.com/questions/53876767/cmake-not-finding-jni-when-java-home-is-set-correctly). 

If you don't mind, @Craigacp , can you please share what is the output of  ` ls $JAVA_HOME` on your machine? 


Also, note that I was suspecting something wrong with `cmake` installed through `brew` so I installed the binary from cmake official site, that's why you see `/Applications/CMake.app/Contents/share/cmake` in the error log I posted. 


On a different note, are there plans of shipping CoreML JNI binary through Maven packages? Given there are already binaries available in the jar file, I think it will be a good idea - a lot of people will be running into build issues otherwise.

**Comment by Craigacp** [comment]
Ahh. It seems like homebrew packages OpenJDK oddly, so `/opt/homebrew/opt/openjdk` isn't quite the right place. For homebrew JDKs I have `/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home` which looks like it's got the right things in it. The CMake detection wants to find the libraries to make sure it's got it, and the other folder doesn't have a `lib`.

I don't know if there are plans to include CoreML in the Maven package, the binary is already pretty large and it would complicate the packaging (as I think you'd need to build on a specific version of macOS). That's a question for the ORT developers though, I just maintain the Java API, I'm not responsible for it's packaging.

**Comment by gauravphoenix** [comment]
Gotcha. I tried cleaning up cmake cache, but now I am getting the error- 

```
/Users/<redacted>/onnxruntime/build/MacOS/Release/_deps/flatbuffers-src/src/idl_gen_rust.cpp:409:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
    size_t i = 0;
    ```
    
The command I am running is `./build.sh  --build_java --config Release --parallel --use_coreml` ; it _feels_ like the code is auto-generated so I am hesitant to hack my way around it. 

Any suggestions on how to go about fixing it?

**Comment by Craigacp** [comment]
You should make sure you've run a build with `--update` as adding the CoreML flag on it's own might change the build options. You also need to add the `--build` flag, I don't know if it's automatically implied by the other ones.

I'm using the latest XCode on my M1 along with macOS 13.4, that might be important, I know there were changes to CoreML in the past few months and it didn't build correctly for me when I tried it in March.

**Comment by edgchen1** [comment]
> Gotcha. I tried cleaning up cmake cache, but now I am getting the error-
> 
> ```
> /Users/<redacted>/onnxruntime/build/MacOS/Release/_deps/flatbuffers-src/src/idl_gen_rust.cpp:409:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
>     size_t i = 0;
> ```
> 
> The command I am running is `./build.sh --build_java --config Release --parallel --use_coreml` ; it _feels_ like the code is auto-generated so I am hesitant to hack my way around it.
> 
> Any suggestions on how to go about fixing it?

ORT doesn't build on Xcode 14.3 now without some modifications. Here's a workaround for that particular issue:

https://github.com/microsoft/onnxruntime/pull/15878/files#diff-cf577ff910eb6272a6a671d1c3eeb1b3b5a6d24357332306e37f8ea533b8cf2d

#15878 should get things building again.

**Comment by gauravphoenix** [comment]
Thank you, @edgchen1  and @Craigacp; I was able to build the library and load an onnx model successfully after applying the changes that both of you have published. 

FWIW, if anyone else is blocked, here are the steps- 

1. checkout @edgchen1 's branch https://github.com/microsoft/onnxruntime/pull/15878 and then apply @Craigacp branch https://github.com/microsoft/onnxruntime/pull/16231

2. build using - 
```
./build.sh --config Release --build_java  --skip_submodule_sync --parallel --skip_tests --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64 --use_coreml
```
3. Done! You should have `./build/MacOS/Release/java/build/libs/onnxruntime-1.16.0.jar` 

Note that I am purposefully skipping tests here due to test failures, @edgchen1 - FYI.

**Comment by edgchen1** [comment]
> Note that I am purposefully skipping tests here due to test failures, @edgchen1 - FYI.

Would you mind sharing which particular tests failed?

**Comment by gauravphoenix** [comment]
Sure, here is a sample output- 
```
9: Test command: /Users/redacted/work/onnxruntime/build/MacOS/Release/onnxruntime_logging_apis_test "--gtest_output=xml:/Users/redacted/work/onnxruntime/build/MacOS/Release/onnxruntime_logging_apis_test.Release.results.xml"
9: Working Directory: /Users/redacted/work/onnxruntime/build/MacOS/Release
9: Test timeout computed to be: 10800
9: [==========] Running 5 tests from 2 test suites.
9: [----------] Global test environment set-up.
9: [----------] 4 tests from RealCAPITestsFixture
9: [ RUN      ] RealCAPITestsFixture.CCppApiLoggerGetLoggingSeverityLevel
9: [       OK ] RealCAPITestsFixture.CCppApiLoggerGetLoggingSeverityLevel (0 ms)
9: [ RUN      ] RealCAPITestsFixture.CApiLoggerLogMessage
9: 0xdeadbeef@2023-06-05 17:10:21.318629 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:157 TestBody Hello
9: 0xdeadbeef@2023-06-05 17:10:21.318658 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:161 TestBody Hello2
9: [       OK ] RealCAPITestsFixture.CApiLoggerLogMessage (0 ms)
9: [ RUN      ] RealCAPITestsFixture.CppApiORTCXXLOG
9: ORT_CXX_LOG@2023-06-05 17:10:21.318679 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:193 TestBody Hello
9: ORT_CXX_LOG@2023-06-05 17:10:21.318692 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:196 TestBody Hello2
9: [       OK ] RealCAPITestsFixture.CppApiORTCXXLOG (0 ms)
9: [ RUN      ] RealCAPITestsFixture.CppApiORTCXXLOGF
9: ORT_CXX_LOGF@2023-06-05 17:10:21.318710 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:234 TestBody Hello
9: ORT_CXX_LOGF@2023-06-05 17:10:21.318722 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:238 TestBody Hello ORT_CXX_LOGF 238
9: ORT_CXX_LOGF@2023-06-05 17:10:21.318736 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:242 TestBody Hello
9: ORT_CXX_LOGF@2023-06-05 17:10:21.318749 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:246 TestBody Hello world 1.200000
9: ORT_CXX_LOGF@2023-06-05 17:10:21.318763 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:251 TestBody Long string: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
9: [       OK ] RealCAPITestsFixture.CppApiORTCXXLOGF (0 ms)
9: [----------] 4 tests from RealCAPITestsFixture (0 ms total)
9:
9: [----------] 1 test from MockCAPITestsFixture
9: [ RUN      ] MockCAPITestsFixture.CppLogMacroBypassCApiCall
9: [       OK ] MockCAPITestsFixture.CppLogMacroBypassCApiCall (0 ms)
9: [----------] 1 test from MockCAPITestsFixture (0 ms total)
9:
9: [----------] Global test environment tear-down
9: [==========] 5 tests from 2 test suites ran. (0 ms total)
9: [  PASSED  ] 5 tests.
9/9 Test #9: onnxruntime_logging_apis_test ...........   Passed    0.12 sec

33% tests passed, 6 tests failed out of 9

Total Test time (real) =   8.76 sec

The following tests FAILED:
	  1 - onnxruntime_test_all (ILLEGAL)
	  2 - onnx_test_pytorch_converted (ILLEGAL)
	  3 - onnx_test_pytorch_operator (ILLEGAL)
	  4 - onnxruntime_shared_lib_test (ILLEGAL)
	  5 - onnxruntime_global_thread_pools_test (ILLEGAL)
	  7 - onnxruntime4j_test (Failed)
```
I am also attaching `LastTest.log`  
[LastTest.log](https://github.com/microsoft/onnxruntime/files/11658680/LastTest.log)

**Comment by gauravphoenix** [comment]
Unfortunately, although I was able to load the model just fine, I couldn't infer anything from it due to JVM crashes, these crashes are visible in the test failures also. 

I tried using JDK 20 also but same result- JVM crashed when it makes the JNI call to run the input against model.

**Comment by edgchen1** [comment]
> Sure, here is a sample output-
> 
> ```
> 9: Test command: /Users/redacted/work/onnxruntime/build/MacOS/Release/onnxruntime_logging_apis_test "--gtest_output=xml:/Users/redacted/work/onnxruntime/build/MacOS/Release/onnxruntime_logging_apis_test.Release.results.xml"
> 9: Working Directory: /Users/redacted/work/onnxruntime/build/MacOS/Release
> 9: Test timeout computed to be: 10800
> 9: [==========] Running 5 tests from 2 test suites.
> 9: [----------] Global test environment set-up.
> 9: [----------] 4 tests from RealCAPITestsFixture
> 9: [ RUN      ] RealCAPITestsFixture.CCppApiLoggerGetLoggingSeverityLevel
> 9: [       OK ] RealCAPITestsFixture.CCppApiLoggerGetLoggingSeverityLevel (0 ms)
> 9: [ RUN      ] RealCAPITestsFixture.CApiLoggerLogMessage
> 9: 0xdeadbeef@2023-06-05 17:10:21.318629 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:157 TestBody Hello
> 9: 0xdeadbeef@2023-06-05 17:10:21.318658 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:161 TestBody Hello2
> 9: [       OK ] RealCAPITestsFixture.CApiLoggerLogMessage (0 ms)
> 9: [ RUN      ] RealCAPITestsFixture.CppApiORTCXXLOG
> 9: ORT_CXX_LOG@2023-06-05 17:10:21.318679 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:193 TestBody Hello
> 9: ORT_CXX_LOG@2023-06-05 17:10:21.318692 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:196 TestBody Hello2
> 9: [       OK ] RealCAPITestsFixture.CppApiORTCXXLOG (0 ms)
> 9: [ RUN      ] RealCAPITestsFixture.CppApiORTCXXLOGF
> 9: ORT_CXX_LOGF@2023-06-05 17:10:21.318710 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:234 TestBody Hello
> 9: ORT_CXX_LOGF@2023-06-05 17:10:21.318722 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:238 TestBody Hello ORT_CXX_LOGF 238
> 9: ORT_CXX_LOGF@2023-06-05 17:10:21.318736 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:242 TestBody Hello
> 9: ORT_CXX_LOGF@2023-06-05 17:10:21.318749 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:246 TestBody Hello world 1.200000
> 9: ORT_CXX_LOGF@2023-06-05 17:10:21.318763 E:onnxruntime:/Users/redacted/work/onnxruntime/onnxruntime/test/logging_apis/test_logging_apis.cc:251 TestBody Long string: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> 9: [       OK ] RealCAPITestsFixture.CppApiORTCXXLOGF (0 ms)
> 9: [----------] 4 tests from RealCAPITestsFixture (0 ms total)
> 9:
> 9: [----------] 1 test from MockCAPITestsFixture
> 9: [ RUN      ] MockCAPITestsFixture.CppLogMacroBypassCApiCall
> 9: [       OK ] MockCAPITestsFixture.CppLogMacroBypassCApiCall (0 ms)
> 9: [----------] 1 test from MockCAPITestsFixture (0 ms total)
> 9:
> 9: [----------] Global test environment tear-down
> 9: [==========] 5 tests from 2 test suites ran. (0 ms total)
> 9: [  PASSED  ] 5 tests.
> 9/9 Test #9: onnxruntime_logging_apis_test ...........   Passed    0.12 sec
> 
> 33% tests passed, 6 tests failed out of 9
> 
> Total Test time (real) =   8.76 sec
> 
> The following tests FAILED:
> 	  1 - onnxruntime_test_all (ILLEGAL)
> 	  2 - onnx_test_pytorch_converted (ILLEGAL)
> 	  3 - onnx_test_pytorch_operator (ILLEGAL)
> 	  4 - onnxruntime_shared_lib_test (ILLEGAL)
> 	  5 - onnxruntime_global_thread_pools_test (ILLEGAL)
> 	  7 - onnxruntime4j_test (Failed)
> ```
> 
> I am also attaching `LastTest.log` [LastTest.log](https://github.com/microsoft/onnxruntime/files/11658680/LastTest.log)

Thanks. I have not seen this (ILLEGAL) status before. Do those test executables just crash?

Unfortunately, I wasn't able to reproduce the failures locally. One notable difference is that I did not build with `--cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64` as I have an Intel Mac.

**Comment by Craigacp** [comment]
I can reproduce them on my M1 Mac. Is there something I can capture that would help?

**Comment by edgchen1** [comment]
> I can reproduce them on my M1 Mac. Is there something I can capture that would help?

Yes, it would be great if you could capture a callstack at the point where it crashes. Maybe from a RelWithDebInfo or Debug build. Thanks in advance!

**Comment by Craigacp** [comment]
On a clean checkout of https://github.com/microsoft/onnxruntime/pull/15878 with my changes in https://github.com/microsoft/onnxruntime/pull/16231, built using `./build.sh --update --config Debug --build --build_java --parallel` on a 2020 M1 13" MBP, macOS 13.4 with XCode 14.2 I get the attached stack trace log out of the JVM when it goes bang. It was running this test in Java - https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/ai/onnxruntime/InferenceTest.java#L383 which I think was the first test to properly hit MLAS.

It's dying with SIGILL, so maybe it hit an unexpected SIMD instruction from another ARM chip?

[hs_err_pid38482.log](https://github.com/microsoft/onnxruntime/files/11671764/hs_err_pid38482.log)

**Comment by edgchen1** [comment]
> On a clean checkout of #15878 with my changes in #16231, built using `./build.sh --update --config Debug --build --build_java --parallel` on a 2020 M1 13" MBP, macOS 13.4 with XCode 14.2 I get the attached stack trace log out of the JVM when it goes bang. It was running this test in Java - https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/ai/onnxruntime/InferenceTest.java#L383 which I think was the first test to properly hit MLAS.
> 
> It's dying with SIGILL (which means it hit an illegal instruction), so maybe it hit an unexpected SIMD instruction from another ARM chip? I usually see SIGILL when Rosetta hits an Intel AVX instruction, but this is an ARM64 binary so I don't know what's going on.
> 
> [hs_err_pid38482.log](https://github.com/microsoft/onnxruntime/files/11671764/hs_err_pid38482.log)

Thanks for testing it out. This looks like something related to MLAS. And just to double check, this build was without `--use_coreml` right?

@yufenglee @chenfucn Can you help take a look at this crash on MacOS ARM64?

**Comment by edgchen1** [comment]
Merged the PRs but keeping this issue open for now.

**Comment by chenfucn** [comment]
C  [libonnxruntime.dylib+0x2470100]  MLAS_PLATFORM::MLAS_PLATFORM()+0x84

Is it possible we can get some symbolic information with this crash, and find out the source line where it crashed? this part of the code hasn't changed for quite some time.

**Comment by Craigacp** [comment]
I compiled it in debug mode is there something else I should do to get the line level information?

**Comment by gauravphoenix** [comment]
@Craigacp - what parameters did you use to build? I used the `--config Debug` hoping it would create `.dylib` with debug symbols but when I run `find ./build/MacOS/Debug -name '*.dylib' | xargs dsymutil` I see no results. This implies that some `cmake` level config needs to set for the debug symbols to be available. 

I haven't done C/C++ development in decades so if anyone can chime in, I am happy to build the library and upload it somewhere for debugging.

**Comment by gauravphoenix** [comment]
Hey folks, any update on this?

**Comment by edgchen1** [comment]
Verified that the illegal instruction error happens on a M1. Fixed an issue and got unit tests passing in #16763. Also tested with `--use_coreml`.
