### PR TITLE
Remove build_java from mac CI pipeline because it is unstable

### PR DESCRIPTION
**Pull request by snnn**
**Description**:

Remove build_java from mac CI pipeline because it is unstable

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by gwang-msft — COMMENTED** [review]
If you are talking about the Gradle error in MacOS pipeline.
The Gradle error can be mitigated using this fix #7364, I did not fix MacOS because the gradle error will not cause build failure. It seems the recent failures in MacOS are caused by npm/js, not java

**Comment by snnn** [comment]
I see. So there are two errors: 

1. error TS2688: Cannot find type definition file for 'normalize-package-data'.
2. net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)

I got them from:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=390476&view=logs&j=7636b40b-abcf-5c6b-cc48-bcd7d4ae0854&t=4f922874-195a-5571-f5f1-e2f658fa1687

Are they both critical?

**Comment by fs-eire** [comment]
> I see. So there are two errors:
> 
> 1. error TS2688: Cannot find type definition file for 'normalize-package-data'.
> 2. net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)
> 
> I got them from:
> https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=390476&view=logs&j=7636b40b-abcf-5c6b-cc48-bcd7d4ae0854&t=4f922874-195a-5571-f5f1-e2f658fa1687
> 
> Are they both critical?

The first one should be related to JS library: onnxruntime-common. But this is wired, I cannot think of any reason for this error. Does this error occur multiple times?

**Comment by gwang-msft** [comment]
> I see. So there are two errors:
> 
> 1. error TS2688: Cannot find type definition file for 'normalize-package-data'.
> 2. net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)
> 
> I got them from:
> https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=390476&view=logs&j=7636b40b-abcf-5c6b-cc48-bcd7d4ae0854&t=4f922874-195a-5571-f5f1-e2f658fa1687
> 
> Are they both critical?

The Gradle error is in every MacOS CI run (pass or fail), it is not critical, but can be mitigated by same fix in #7364
