### ISSUE TITLE
Build failure master branch in selector_action_transformer.cc in optimizer code

### ISSUE THREAD

**Issue by georgen117** [microsoft/onnxruntime#10235]
**Describe the bug**
I have been unable to build Onnxruntime using the tip of master for the past few days.

using git bisect to find the first commit that caused build issues.

```
792db33f0140cf8c43a32d7cad7e8c8110a1fe49 is the first bad commit
commit 792db33f0140cf8c43a32d7cad7e8c8110a1fe49
Author: Edward Chen <18449977+edgchen1@users.noreply.github.com>
Date:   Tue Jan 4 12:09:07 2022 -0800

    Enable loading of ORT format model graph runtime optimizations (#9901)

    Initial implementation of load/replay of runtime optimizations in an ORT format model.
```

command used to build the code:
```
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019"
```

copy-paste of the error from visual studio. (I personally found its error clearer than the command line output)

```
24>qdq_selector_action_transformer.cc
24>selector_action_transformer.cc
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core\optimizer\selectors_actions\selector_action_transformer.cc(69,32): error C2280: 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry(const onnxruntime::SelectorActionRegistry &)': attempting to reference a deleted function
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core/optimizer/selectors_actions/selector_action_transformer.h(73): message : see declaration of 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry'
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core/optimizer/selectors_actions/selector_action_transformer.h(73,3): message : 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry(const onnxruntime::SelectorActionRegistry &)': function was explicitly deleted (compiling source file C:\Users\georgena\workspace\onnxruntime\onnxruntime\core\optimizer\selectors_actions\selector_action_transformer.cc)
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core\optimizer\qdq_transformer\selectors_actions\qdq_selector_action_transformer.cc(148): error C2280: 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry(void) noexcept': attempting to reference a deleted function
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core/optimizer/selectors_actions/selector_action_transformer.h(68): message : see declaration of 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry'
24>C:\Users\georgena\workspace\onnxruntime\onnxruntime\core/optimizer/selectors_actions/selector_action_transformer.h(68,3): message : 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry(void) noexcept': function was implicitly deleted because the explicit exception specification is incompatible with that of the implicit declaration (compiling source file C:\Users\georgena\workspace\onnxruntime\onnxruntime\core\optimizer\qdq_transformer\selectors_actions\qdq_selector_action_transformer.cc)
24>Done building project "onnxruntime_optimizer.vcxproj" -- FAILED.
```

**Urgency**
I expect this is a high urgency issue since it will start to affect all teams trying to develop code based on the master branch

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: N/A
- Visual Studio version (if applicable): VS2019 version 16.7.7 Microsoft .NET Framework Version 4.8.04084
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
checkout master branch (or 792db33f0140cf8c43a32d7cad7e8c8110a1fe49 )
build using `.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019"`

**Expected behavior**
Should build and pass unit tests without failure

**Comment by georgen117** [comment]
I just tried to build the tip of master on Linux and had no problems.  So this appears to be a Windows/Visual Studio issue.

**Comment by edgchen1** [comment]
Was unable to reproduce the error in VS2019 16.11.8.
Actually, it looks like this was addressed by: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1286r2.html
See also:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1286r2.html#existing-approach-prevents-a-useful-feature
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1286r2.html#approach

In short, taking the move constructor as an example, `X(X&&) noexcept = default;` now says that the defaulted move constructor is noexcept instead of possibly being deleted if the implicit move constructor has a different exception specification.

It was implemented in VS2019 16.8. Search for P1286R2 here: https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170

Are you able to use VS2019 16.8 or later?

**Comment by snnn** [comment]
He said "VS2019 version 16.7.7"

**Comment by georgen117** [comment]
I have a coworker that tried to reproduce the error and did not see any issue.  I have done a completely clean build and it still happens on my system. I really hope this is not a "It fails only on my system" type issue.  I will try and update VS.

**Comment by georgen117** [comment]
@edgchen1 it looks like you identified the issue.  I was able to update VS to 16.11.8 (the latest version as far as I know) and it built fine.  Since this is not causing me any further problems I am going to close the ticket.  I will leave it to others if you need to add to or update any build documentation.
