### ISSUE TITLE
Support eigen release

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#877]
This is a common issue.

Seems onnxruntime wants eigen master.
The latest release of eigen, 3.3.7, hasn't include the GPU dir yet.
It only has CUDA, which should be almost equivalent to those files under GPU.

Should we check with `__has_include` (or other compiler equivalent in pre-17 C++)?

```
FAILED: CMakeFiles/onnxruntime_providers.dir/tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc.o 
ccache /opt/rh/devtoolset-8/root/usr/bin/g++  -DONNX_ML -DONNX_NAMESPACE=onnx -DORT_RUN_EXTERNAL_ONNX_TESTS -DPLATFORM_POSIX -DUSE_FULL_PROTOBUF -DUSE_MKLML=1 -DUSE_MKLML_FOR_BLAS=1 -DUSE_MLAS -DUSE_OPENBLAS=1 -DUSE_OPENMP -I/tmp/scratch/onnxruntime/include/onnxruntime -Imklml/src/project_mklml/include -I/tmp/scratch/onnxruntime/cmake/external/nsync/public -I. -I/tmp/scratch/onnxruntime/cmake/external/gsl -I/tmp/scratch/onnxruntime/cmake/external/gsl/include -I/tmp/scratch/onnxruntime/cmake/external/onnx -I/tmp/scratch/onnxruntime/cmake/external/protobuf/src -Ionnx/.. -I/tmp/scratch/onnxruntime/onnxruntime -I/usr/local/include/eigen3 -I/tmp/scratch/onnxruntime/onnxruntime/../cmake/external/gemmlowp -I/tmp/scratch/onnxruntime/onnxruntime/../cmake/external/re2 -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -fopenmp -DGSL_THROW_ON_CONTRACT_VIOLATION -Wall -Wextra -ffunction-sections -fdata-sections -Wno-error=sign-compare -Wno-parentheses -O3 -DNDEBUG -march=native -mtune=native -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -flto -fno-fat-lto-objects -fPIC   -std=gnu++14 -MD -MT CMakeFiles/onnxruntime_providers.dir/tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc.o -MF CMakeFiles/onnxruntime_providers.dir/tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc.o.d -o CMakeFiles/onnxruntime_providers.dir/tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc.o -c /tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc
/tmp/scratch/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc:10:10: fatal error: Eigen/src/Core/arch/GPU/Half.h: No such file or directory
 #include "Eigen/src/Core/arch/GPU/Half.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**System information**
- ONNX Runtime version (you are using): master

**Comment by pranavsharma** [comment]
@snn you upgraded eigen recently. can you take a look?

**Comment by snnn** [comment]
We never planned to support multiple versions of any of our third-party dependencies. 
It's not a bug or issue.

**Comment by snnn** [comment]
Yes, onnxruntime wants a commit from eigen master. The current onnxruntime master doesn't work with eigen 3.3.7.

**Comment by xkszltl** [comment]
@snnn May I ask which feature from master is used, except the path/namespace change?

**Comment by xkszltl** [comment]
FYI I don't think this is a bug/regression.
That's why I open it as `Feature Request`.
But I just wonder, for a library, if it's too aggressive to use master only feature without backward compatibility to any formal release.

**Comment by snnn** [comment]
> May I ask which feature from master is used, except the path/namespace change?

@xkszltl This change is for an upcoming PR. The second PR will be very big, so I split them.  So please allow me answer this question later.

> it's too aggressive to use master only feature without backward compatibility to any formal release
This is not specific to eigen. We have the same issue with ONNX. We will consider your concern.  Welcome to write to us with more evidence elaboration.

**Comment by xkszltl** [comment]
Thanks for clarification.
