### PR TITLE
[QNN EP] Add better unit tests for rank 5 ReduceSum

### PR DESCRIPTION
**Pull request by adrianlizarraga**
### Description
We previously had a unit test that checked that QNN EP rejected rank 5 reduce ops. This PR:
- Allows the underlying QNN APIs to validate the input rank for Reduce ops.
- Modifies a rank 5 ReduceSum unit test so that it can be used to reproduce a graph finalization error on QNN SDK 2.15.1.
- Adds a new rank 5 ReduceSum unit test with a configuration that is known to work in QNN SDK 2.15.1.

### Motivation and Context
Allows us to more easily test/verify rank 5 support for ReduceSum.

### CODE REVIEW

File: onnxruntime/core/providers/qnn/builder/opbuilder/reduce_op_builder.cc [hunk 1]
```diff
@@ -188,13 +188,6 @@ Status ReduceOpBuilder::IsOpSupported(QnnModelWrapper& qnn_model_wrapper,
     return ORT_MAKE_STATUS(ONNXRUNTIME, FAIL, "QNN EP: ReduceProd operator not supported by HTP backend.");
   }
 
-  if (is_npu_backend) {
```
Comment (adrianlizarraga) [inline onnxruntime/core/providers/qnn/builder/opbuilder/reduce_op_builder.cc:191]: Allow QNN APis to validate shape

File: onnxruntime/test/providers/qnn/reduce_op_test.cc [hunk 2]
```diff
@@ -465,14 +465,34 @@ TEST_F(QnnHTPBackendTests, ReduceSumS8Opset13_NoKeepDims) {
...
-TEST_F(QnnHTPBackendTests, ReduceSumS8Opset13_Rank5Unsupported) {
+// Test rank 5 ReduceSum (s8 quant) with axes = [0, 1, 2, 3, 4], keep_dims = true
+// TODO: QNN 2.15.1 Graph finalization error:
+// graph_prepare.cc:234:ERROR:could not create op: q::Sum
+// graph_prepare.cc:1093:ERROR:Op 0x102500000011 preparation failed with err:-1
+// Completed stage: Graph Transformations and Optimizations (17163 us)
+// QnnDsp <E> "node_token_3" generated: could not create op
+// QnnDsp <E> RouterWindows graph prepare failed 12
+// QnnDsp <E> Failed to finalize graph (id: 1) with err 1002{}
+TEST_F(QnnHTPBackendTests, DISABLED_ReduceSumS8Opset13_Rank5) {
```
Comment (adrianlizarraga) [inline onnxruntime/test/providers/qnn/reduce_op_test.cc:476]: THis test fails on QNN 2.15.1. This is what was reported to QC.

File: onnxruntime/test/providers/qnn/reduce_op_test.cc [hunk 3]
```diff
@@ -465,14 +465,34 @@ TEST_F(QnnHTPBackendTests, ReduceSumS8Opset13_NoKeepDims) {
...
                              {0, 1, 2, 3, 4},  // axes
                              true,             // keepdims
                              13,               // opset
-                             ExpectedEPNodeAssignment::None);
+                             ExpectedEPNodeAssignment::All);
+}
+
+// Test rank 5 ReduceSum (u8 quant) with axes = [-1], keep_dims = false
+// TODO: Enable on QNN 2.15.1 (works fine)
+TEST_F(QnnHTPBackendTests, DISABLED_ReduceSumS8Opset13_Rank5_LastAxis) {
```
Comment (adrianlizarraga) [inline onnxruntime/test/providers/qnn/reduce_op_test.cc:487]: This works on 2.15.1. Uses the same configuration as our partner model.

File: onnxruntime/core/providers/qnn/builder/opbuilder/reduce_op_builder.cc [hunk 4]
```diff
@@ -188,13 +188,6 @@ Status ReduceOpBuilder::IsOpSupported(QnnModelWrapper& qnn_model_wrapper,
...
-    std::vector<uint32_t> input_shape;
-    ORT_RETURN_IF_NOT(qnn_model_wrapper.GetOnnxShape(node_unit.Inputs()[0].node_arg, input_shape),
-                      "QNN EP: Cannot get input shape for");
-    ORT_RETURN_IF(input_shape.size() > 4, "QNN EP: HTP backend does not support Reduce ops with rank > 4.");
```
Comment (HectorSVC) [inline onnxruntime/core/providers/qnn/builder/opbuilder/reduce_op_builder.cc:195]: >input_shape.size() > 4 [](start = 18, length = 22)

What will happen if rank > 5? Will the Op validation fail as expected? Or we still need to keep code here to prevent that happen?

Comment (adrianlizarraga) [reply onnxruntime/core/providers/qnn/builder/opbuilder/reduce_op_builder.cc:195]: It fails as expected on 2.15.1. I added another unit test for this case.

**Review by HectorSVC — APPROVED** [review]
:shipit:

File: onnxruntime/test/providers/qnn/reduce_op_test.cc [hunk 5]
```diff
@@ -465,14 +465,44 @@ TEST_F(QnnHTPBackendTests, ReduceSumS8Opset13_NoKeepDims) {
...
+                             TestInputDef<float>({1, 3, 4, 4, 2, 1}, false, GetFloatDataInRange(-10.0f, 10.0f, 96)),
+                             {-1},                             // axes
+                             false,                            // keepdims
+                             13,                               // opset
+                             ExpectedEPNodeAssignment::None);  // Not assigned to QNN EP
+}
+
+// Test rank 5 ReduceSum (u8 quant) with axes = [-1], keep_dims = false
+// TODO: Enable on QNN 2.15.1 (works fine)
+TEST_F(QnnHTPBackendTests, DISABLED_ReduceSumS8Opset13_Rank5_LastAxis) {
```
Comment (adrianlizarraga) [inline onnxruntime/test/providers/qnn/reduce_op_test.cc:497]:
```suggestion
TEST_F(QnnHTPBackendTests, DISABLED_ReduceSumU8Opset13_Rank5_LastAxis) {
```

**Review by HectorSVC — APPROVED** [review]
:shipit:
