### ISSUE TITLE
[Build] QNN EP have build error when building on Android platform

### ISSUE THREAD

**Issue by green0765** [microsoft/onnxruntime#26590]
### Describe the issue

I try to build QNN EP on Android platform. It report error:

onnxruntime/onnxruntime/core/providers/qnn/builder/opbuilder/upsample_op_builder.cc:165:109: error: use of undeclared identifier 'QNN_OP_RESIZE_BILINEAR_PARAM_ANTIALIAS'

This issue should be caused by https://github.com/microsoft/onnxruntime/pull/24646.
I suppose it depends on certain QNN SDK version, but I don't know which version I should use. What I'm using now is 2.24.0.240626.

onnxruntime branch: rel-1.23.0
NDK version:  r29.
QNN SDK version: 2.24.0.240626
compile platform: Ubuntu 22.04

BTW, there's unused function warning of function IsQuant16bit in onnxruntime/core/providers/qnn/builder/opbuilder/matmul_op_builder.cc. 
It easy to work around locally but should be fixed.

### Target platform

Android

### Build script

./build.sh --android --android_sdk_path /data/Android/ --android_ndk_path /data/Android/ndk/androi
d-ndk-r29 --android_abi arm64-v8a --android_api 27 --use_qnn static_lib --qnn_home /data/qnn/2.24.0.240626

### Error / output

/data/onnxruntime/onnxruntime/core/providers/qnn/builder/opbuilder/upsample_op_builder.cc:165:109: error: use of undeclared identifier 'QNN_OP_RESIZE_BILINEAR_PARAM_ANTIALIAS'
  165 |       ORT_RETURN_IF_ERROR(AddQnnScalar<bool>(qnn_model_wrapper, node_unit.Index(), node_unit.Name(), false, QNN_OP_RESIZE_BILINEAR_PARAM_ANTIALIAS, param_tensor_names));
      |                                                                                                             ^
1 error generated.
gmake[2]: *** [CMakeFiles/onnxruntime_providers_qnn.dir/build.make:527: CMakeFiles/onnxruntime_providers_qnn.dir/data/onnxruntime/onnxruntime/core/providers/qnn/builder/opbuilder/upsample_op_builder.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1682: CMakeFiles/onnxruntime_providers_qnn.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/data/onnxruntime/tools/ci_build/build.py", line 2670, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/onnxruntime/tools/ci_build/build.py", line 2571, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/data/onnxruntime/tools/ci_build/build.py", line 1363, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/data/onnxruntime/tools/ci_build/build.py", line 148, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/onnxruntime/tools/python/util/run.py", line 50, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/home/guawu/miniconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/guawu/.local/bin/cmake', '--build', '/data/onnxruntime/build/Android/Debug', '--config', 'Debug']' returned non-zero exit status 2.

**Comment by edgchen1** [comment]
try QNN SDK 2.37 or later. that is what the QNN EP is compiled with on rel-1.23.0.

https://github.com/microsoft/onnxruntime/blob/d70213d40ea99b2665a85096ae0a1b993a608963/tools/ci_build/github/azure-pipelines/templates/jobs/download_linux_qnn_sdk.yml#L4

**Comment by green0765** [comment]
2.37.1.250807 works for me. Thanks!
