### ISSUE TITLE
clang++: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by rjharahul21** [microsoft/onnxruntime#17261]
### Describe the issue

I am trying to add my own api and creating build/Android/Debug/libonnxruntime.so file for android so i am using this commad and getting this error.

### Urgency

Very important

### Target platform

android

### Build script

./build.sh --android --android_sdk_path /home/test/Android/SDK/Sdk/ --android_ndk_path /home/test/A  ndroid/NDK/android-ndk-r21e/ --build_shared_lib

### Error / output

[100%] Built target onnxruntime_mlas_test
[100%] Built target custom_op_library
[100%] Linking CXX executable onnxruntime_customopregistration_test
/home/test/Android/NDK/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch6  4-linux-android/bin/ld: warning: liblog.so, needed by libonnxruntime.so, not found (try using -rpath or -rpath-link)
libonnxruntime.so: undefined reference to `__android_log_write'
libonnxruntime.so: undefined reference to `__android_log_print'
libonnxruntime.so: undefined reference to `__android_log_vprint'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/onnxruntime_customopregistration_test.dir/build.make:151: onnxruntime_customopregistration_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:2594: CMakeFiles/onnxruntime_customopregistration_test.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/test/onnxruntime/tools/ci_build/build.py", line 2636, in <module>
    sys.exit(main())
  File "/home/test/onnxruntime/tools/ci_build/build.py", line 2529, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/test/onnxruntime/tools/ci_build/build.py", line 1440, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/test/onnxruntime/tools/ci_build/build.py", line 789, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/test/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 517, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/test/.local/bin/cmake', '--build', '/home/test/onnxruntime/build/Android/Debug', '--  config', 'Debug']' returned non-zero exit status 2.

**Comment by skottmckay** [comment]
The build with the latest main works with NDK 25.1 for x86_64 (`--android_abi=x86_64`). Is it just the arm64 build with this issue or does x86_64 also fail for you?

Can you use a more recent NDK version?

Failing that you could try explicitly adding liblog to the test binary in question with this change: https://github.com/microsoft/onnxruntime/compare/skottmckay/AddLogLibraryToCustomOpsUnitTest

Or you could skip building all the unit tests with `--cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF`
