### ISSUE TITLE
[Build] error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "bool"

### ISSUE THREAD

**Issue by shyn** [microsoft/onnxruntime#25574]
### Describe the issue

Could not build with master or v1.22.1 on windows(x64). Error C1189 but I couldn't find any "define bool macro" code.

### Target platform

Windows

### Build script

.\build.bat --build_nuget --use_winml --use_dml --build_shared_lib --config Release --parallel --enable_wcos --skip_submodule_sync --skip_tests

### Error / output

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35
207\include\xkeycheck.h(52,1): error C1189: #error:  The C++ Standard Library
forbids macroizing the keyword "bool". Enable warning C4005 to find the forbid
den define. [C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Windows\Release\o
nnxruntime_providers.vcxproj]
  (compiling source file '../../../onnxruntime/core/providers/cpu/cpu_provider
  _factory.cc')

  cpu_provider_shared.cc
  absl_examine_stack.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\buil
  d\Windows\Release\_deps\abseil_cpp-build\absl\debugging\Release\absl_examine
  _stack.lib
  absl_crc32c.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Windo
  ws\Release\_deps\abseil_cpp-build\absl\crc\Release\absl_crc32c.lib
  absl_kernel_timeout_internal.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1
  .22.1\build\Windows\Release\_deps\abseil_cpp-build\absl\synchronization\Rele
  ase\absl_kernel_timeout_internal.lib
  absl_log_internal_globals.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22
  .1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_in
  ternal_globals.lib
  absl_log_entry.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Wi
  ndows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_entry.lib
  absl_flags_marshalling.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\
  build\Windows\Release\_deps\abseil_cpp-build\absl\flags\Release\absl_flags_m
  arshalling.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/synchronization/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/crc/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  onnxruntime_optimizer.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\b
  uild\Windows\Release\Release\onnxruntime_optimizer.lib
  crc_cord_state.cc
  log_format.cc
  win32_waiter.cc
  absl_crc_cord_state.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\bui
  ld\Windows\Release\_deps\abseil_cpp-build\absl\crc\Release\absl_crc_cord_sta
  te.lib
  sem_waiter.cc
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/strings/CMakeLists.txt
  absl_log_internal_format.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.
  1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_int
  ernal_format.lib
  per_thread_sem.cc
  cord_rep_crc.cc
  log_sink.cc
  cord_internal.cc
  cord_rep_btree.cc
  futex_waiter.cc
  absl_log_sink.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Win
  dows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_sink.lib
  barrier.cc
  notification.cc
  mutex.cc
  cord_rep_consume.cc
  cord_rep_btree_navigator.cc
  range.cc
  cord_rep_btree_reader.cc
  fp16_pool.cc
  clip.cc
  constant_of_shape.cc
  cumsum.cc
  create_thread_identity.cc
  random.cc
  pthread_waiter.cc
  blocking_counter.cc
C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Windows\Release\_deps\abseil_c
pp-src\absl\synchronization\mutex.cc(1335,18): warning C4267: '+=': conversion
 from 'size_t' to 'int', possible loss of data [C:\Users\aiman\Desktop\onnxrun
time-1.22.1\build\Windows\Release\_deps\abseil_cpp-build\absl\synchronization\
absl_synchronization.vcxproj]
  waiter_base.cc
  stdcpp_waiter.cc
  absl_cord_internal.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\buil
  d\Windows\Release\_deps\abseil_cpp-build\absl\strings\Release\absl_cord_inte
  rnal.lib
  fp16_conv.cc
  absl_synchronization.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\bu
  ild\Windows\Release\_deps\abseil_cpp-build\absl\synchronization\Release\absl
  _synchronization.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/strings/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/flags/CMakeLists.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/container/CMakeLists.txt
  vlog_config.cc
  cordz_handle.cc
  program_name.cc
  hashtablez_sampler_force_weak_definition.cc
  hashtablez_sampler.cc
  absl_cordz_handle.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build
  \Windows\Release\_deps\abseil_cpp-build\absl\strings\Release\absl_cordz_hand
  le.lib
  absl_flags_program_name.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1
  \build\Windows\Release\_deps\abseil_cpp-build\absl\flags\Release\absl_flags_
  program_name.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/strings/CMakeLists.txt
  absl_hashtablez_sampler.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1
  \build\Windows\Release\_deps\abseil_cpp-build\absl\container\Release\absl_ha
  shtablez_sampler.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/flags/CMakeLists.txt
  usage_config.cc
  cordz_info.cc
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/container/CMakeLists.txt
  absl_vlog_config_internal.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22
  .1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_vlog_c
  onfig_internal.lib
  raw_hash_set.cc
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  globals.cc
  absl_flags_config.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build
  \Windows\Release\_deps\abseil_cpp-build\absl\flags\Release\absl_flags_config
  .lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/flags/CMakeLists.txt
  flag.cc
  absl_cordz_info.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\W
  indows\Release\_deps\abseil_cpp-build\absl\strings\Release\absl_cordz_info.l
  ib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/strings/CMakeLists.txt
  cord.cc
  cord_buffer.cc
  cord_analysis.cc
  absl_raw_hash_set.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build
  \Windows\Release\_deps\abseil_cpp-build\absl\container\Release\absl_raw_hash
  _set.lib
  absl_log_globals.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\
  Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_globals.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  log_sink_set.cc
  absl_flags_internal.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\bui
  ld\Windows\Release\_deps\abseil_cpp-build\absl\flags\Release\absl_flags_inte
  rnal.lib
  absl_log_internal_log_sink_set.vcxproj -> C:\Users\aiman\Desktop\onnxruntime
  -1.22.1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_l
  og_internal_log_sink_set.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  absl_cord.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Windows
  \Release\_deps\abseil_cpp-build\absl\strings\Release\absl_cord.lib
  log_message.cc
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/flags/CMakeLists.txt
  reflection.cc
  absl_log_internal_message.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22
  .1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_in
  ternal_message.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/build/Windows
  /Release/_deps/abseil_cpp-src/absl/log/CMakeLists.txt
  check_op.cc
  absl_log_internal_check_op.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.2
  2.1\build\Windows\Release\_deps\abseil_cpp-build\absl\log\Release\absl_log_i
  nternal_check_op.lib
  absl_flags_reflection.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\b
  uild\Windows\Release\_deps\abseil_cpp-build\absl\flags\Release\absl_flags_re
  flection.lib
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/cmake/CMakeLi
  sts.txt
  Building Custom Rule C:/Users/aiman/Desktop/onnxruntime-1.22.1/cmake/CMakeLi
  sts.txt
  Scanning sources for module dependencies...
  provider_ort_api_init.cc
  my_allocator.cc
  my_ep_factory.cc
  my_ep_data_transfer.cc
  provider_bridge_provider.cc
  my_execution_provider.cc
  cpuid_info.cc
  cpuid_uarch.cc
  helper.cc
  ostream_sink.cc
  capture.cc
  profiler_common.cc
  logging.cc
  profiler.cc
  denormal.cc
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35
207\include\xkeycheck.h(52,1): error C1189: #error:  The C++ Standard Library
forbids macroizing the keyword "bool". Enable warning C4005 to find the forbid
den define. [C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\Windows\Release\t
est_execution_provider.vcxproj]
  (compiling source file '../../../onnxruntime/test/testdata/custom_execution_
  provider_library/my_ep_factory.cc')

  onnxruntime_mlas.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\build\
  Windows\Release\Release\onnxruntime_mlas.lib
  env.cc
  status.cc
  threadpool.cc
  env_time.cc
  make_platform_default_log_sink.cc
  telemetry.cc
  device_discovery.cc
  debug_alloc.cc
  path_lib.cc
  stacktrace.cc
  dll_load_error.cc
  env.cc
  telemetry.cc
  hardware_core_enumerator.cc
  env_time.cc
  etw_sink.cc
  Compiling...
  cpuid_uarch.cc
  cpuid_info.cc
  profiler.cc
  logging.cc
  helper.cc
  capture.cc
  denormal.cc
  ostream_sink.cc
  profiler_common.cc
  threadpool.cc
  env_time.cc
  path_lib.cc
  env.cc
  status.cc
  telemetry.cc
  debug_alloc.cc
  make_platform_default_log_sink.cc
  device_discovery.cc
  env_time.cc
  dll_load_error.cc
  env.cc
  hardware_core_enumerator.cc
  stacktrace.cc
  etw_sink.cc
  telemetry.cc
  onnxruntime_common.vcxproj -> C:\Users\aiman\Desktop\onnxruntime-1.22.1\buil
  d\Windows\Release\Release\onnxruntime_common.lib
Traceback (most recent call last):
  File "C:\Users\aiman\Desktop\onnxruntime-1.22.1\\tools\ci_build\build.py", line 2550, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\aiman\Desktop\onnxruntime-1.22.1\\tools\ci_build\build.py", line 2452, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\Users\aiman\Desktop\onnxruntime-1.22.1\\tools\ci_build\build.py", line 1280, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\aiman\Desktop\onnxruntime-1.22.1\\tools\ci_build\build.py", line 147, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aiman\Desktop\onnxruntime-1.22.1\tools\python\util\run.py", line 50, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "C:\Users\aiman\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\aiman\\scoop\\shims\\cmake.EXE', '--build', 'C:\\Users\\aiman\\Desktop\\onnxruntime-1.22.1\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:48', '/p:CL_MPCount=15', '/nodeReuse:False']' returned non-zero exit status 1.

### Visual Studio Version

2022

**Comment by shyn** [comment]
Only one place I can find the "#define bool". It's the <stdbool.h> at `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\stdbool.h`

But thanks to https://github.com/microsoft/onnxruntime/issues/22213#issuecomment-2373378405 `--cmake_extra_defines FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER` did help!
