### ISSUE TITLE
[Build] onnxruntime fails to build on x86 Intel Mac

### ISSUE THREAD

**Issue by ram95014** [microsoft/onnxruntime#16221]
### Describe the issue

Cloned onnxruntime like so: 
git clone --recursive https://github.com/Microsoft/onnxruntime

Started a build on Mac OS X (Ventura 13.2.1 (22D68)) with Clang version:
/Library/Developer/CommandLineTools/usr/bin/c++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

./build.sh --enable_pybind --config RelWithDebInfo --build_shared_lib  --skip_tests  --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64 --parallel --build_wheel

Build fails with following error message:
<Git>/onnxruntime/build/MacOS/RelWithDebInfo/_deps/flatbuffers-src/src/idl_gen_rust.cpp:409:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]

I fixed this by modifying CMakeLists.txt in build/MacOS/RelWithDebInfo/_debs/flatbuffers-src to not error-out on warnings, and then I got this:
<Git>/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:114:49: error: 'codecvt_utf8<wchar_t, 1114111, 0>' is deprecated [-Werror,-Wdeprecated-declarations]

I'm unable to fix this error. Please help.

### Urgency

Somewhat urgent.

### Target platform

OSX Ventura

### Build script

./build.sh --enable_pybind --config RelWithDebInfo --build_shared_lib  --skip_tests  --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64 --parallel --build_wheel

### Error / output

<Git>/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:114:49: error: 'codecvt_utf8<wchar_t, 1114111, 0>' is deprecated [-Werror,-Wdeprecated-declarations]

### GCC / Compiler Version

Apple clang version 14.0.3 (clang-1403.0.22.14.1) Target: x86_64-apple-darwin22.3.0

**Comment by edgchen1** [comment]
I think these should be addressed by #15878. you can refer to that for the updates/workarounds.

**Comment by ram95014** [comment]
Use --compile_no_warning_as_error with ./build.sh to resolve this issue.
