### PR TITLE
Fix some build issues on MacOS with Xcode 14.3.

### LINKED ISSUE #16221: [Build] onnxruntime fails to build on x86 Intel Mac
### Describe the issue

Cloned onnxruntime like so: 
git clone --recursive https://github.com/Microsoft/onnxruntime

Started a build on Mac OS X (Ventura 13.2.1 (22D68)) with Clang version:
/Library/Developer/CommandLineTools/usr/bin/c++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

./build.sh --enable_pybind --config RelWithDebInfo --build_shared_lib  --skip_tests  --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64 --parallel --build_wheel

Build fails with following error message:
<Git>/onnxruntime/build/MacOS/RelWithDebInfo/_deps/flatbuffers-src/src/idl_gen_rust.cpp:409:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]

I fixed this by modifying CMakeLists.txt in build/MacOS/RelWithDebInfo/_debs/flatbuffers-src to not error-out on warnings, and then I got this:
<Git>/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:114:49: error: 'codecvt_utf8<wchar_t, 1114111, 0>' is deprecated [-Werror,-Wdeprecated-declarations]

I'm unable to fix this error. Please help.

### Urgency

Somewhat urgent.

### Target platform

OSX Ventura

### Build script

./build.sh --enable_pybind --config RelWithDebInfo --build_shared_lib  --skip_tests  --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64 --parallel --build_wheel

### Error / output

<Git>/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:114:49: error: 'codecvt_utf8<wchar_t, 1114111, 0>' is deprecated [-Werror,-Wdeprecated-declarations]

### Visual Studio Version

_No response_

### GCC / Compiler Version

Apple clang version 14.0.3 (clang-1403.0.22.14.1) Target: x86_64-apple-darwin22.3.0

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

- Fix flatbuffers flatc warning, unused-but-set-variable.
- Address `-Wshorten-64-to-32` warnings (fix in our code, allow in dependencies' code).
- Update CI builds to use Xcode 14.3.
- Update minimum iOS version to 12.0.
- Update Mac hosted agents to MacOS 13 where possible.

### Motivation and Context

Fix local build.
Fix #16221.

### CODE REVIEW

File: onnxruntime/core/providers/cpu/nn/string_normalizer.cc [hunk 1]
```diff
@@ -8,11 +8,18 @@
...
+#elif defined(__ANDROID__)
 #include <codecvt>
 #else
 #include <limits>
 #include <iconv.h>
+
+#if defined(__APPLE__)
+// Specify -liconv here so we don't need to add link flags for libiconv elsewhere, e.g., for iOS apps that statically
+// link to ORT.
+asm(".linker_option \"-liconv\"");
```
Comment (snnn) [inline onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: We need to think it again if the iconv library is from GNU.

**Comment by snnn** [comment]
Related #15599

File: onnxruntime/core/providers/cpu/nn/string_normalizer.cc (hunk 1 above)
Comment (edgchen1) [reply onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: I see. what's the situation on Linux?

Comment (snnn) [reply onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: iconv is a part of POSIX standard. So every Linux system must provide it. Most Linux systems use glibc as the C Runtime, and glibc provides iconv  functions. GNU's libiconv is another implementation of the iconv functions. Usually people do not need to use libiconv on Linux.  Since every Linux program needs to use glibc, there is no license concern for glibc.

Comment (snnn) [reply onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: See this: https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx/57734435

**Review by snnn — DISMISSED** [review]

File: cmake/CMakeLists.txt [hunk 2]
```diff
@@ -551,30 +551,31 @@ if (WIN32)
...
   check_cxx_compiler_flag(-Wdeprecated-declarations HAS_DEPRECATED_DECLARATIONS)
-  check_cxx_compiler_flag(-Wclass-memaccess HAS_CLASS_MEMACCESS)
+  check_cxx_compiler_flag(-Wenum-constexpr-conversion HAS_ENUM_CONSTEXPR_CONVERSION)
+  check_cxx_compiler_flag(-Wformat-truncation HAS_FORMAT_TRUNCATION)
+  check_cxx_compiler_flag(-Wignored-attributes HAS_IGNORED_ATTRIBUTES)
   check_cxx_compiler_flag(-Wmaybe-uninitialized HAS_MAYBE_UNINITIALIZED)
+  check_cxx_compiler_flag(-Wmissing-braces HAS_MISSING_BRACES)
+  check_cxx_compiler_flag(-Wnonnull-compare HAS_NONNULL_COMPARE)
+  check_cxx_compiler_flag(-Wparentheses HAS_PARENTHESES)
+  check_cxx_compiler_flag(-Wshorten-64-to-32 HAS_SHORTEN_64_TO_32)
```
Comment (edgchen1) [inline cmake/CMakeLists.txt:570]: added a new one for `-Wshorten-64-to-32`. the other changes are ordering alphabetically

File: onnxruntime/core/providers/cpu/nn/string_normalizer.cc (hunk 1 above)
Comment (edgchen1) [reply onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: according to https://www.gnu.org/software/libiconv/ the libiconv library is licensed under LGPL. is its usage a concern in that case?

Comment (skottmckay) [reply onnxruntime/core/providers/cpu/nn/string_normalizer.cc:20]: Probably a question for CELA to be sure.

https://docs.opensource.microsoft.com/legal/cela-guidance/cela-license-specific-guidance/#distribute-lgplv21-code
https://docs.opensource.microsoft.com/legal/cela-guidance/cela-license-specific-guidance/#distribute-lgplv3-code

**Review by snnn — CHANGES_REQUESTED** [review]
Based on an internal discussion, we have a better choice than this library. We can use the system's builtin APIs.

**Comment by edgchen1** [comment]
> Based on an internal discussion, we cannot use LGPL libraries.

Ok. I will get things building first in this PR by allowing the wstring_convert deprecation warning for now. We can address how to replace it later.

**Review by snnn — DISMISSED** [review]

File: onnxruntime/core/providers/cpu/nn/string_normalizer.cc [hunk 3]
```diff
@@ -13,12 +14,22 @@
...
+
 #endif  // _MSC_VER
 
 #include <locale>
 #include <functional>
 #include <unordered_set>
 
+#if defined(__GNUC__)
+// Allow deprecated-declarations warning - std::wstring_convert is deprecated.
+// TODO find a suitable replacement
```
Comment (edgchen1) [inline onnxruntime/core/providers/cpu/nn/string_normalizer.cc:26]: create a work item for this

**Review by skottmckay — APPROVED** [review]
:shipit:

**Review by snnn — APPROVED** [review]
Thank you!

**Review by vraspar — APPROVED** [review]
