### ISSUE TITLE
[Build] Issue when trying to enable XNNPACK

### ISSUE THREAD

**Issue by wolfviking0** [microsoft/onnxruntime#13598]
### Describe the issue

I am building across different platform and everything was working fine.
I wanted to enable XNNPACK but since I am not able to have a build working :

### Target platform

OSX, Linux x86_64, LinuxArm64

### Build script

PRECOMPILE(
    NAME
    onnx
    URL
    https://github.com/microsoft/onnxruntime.git
    CHECKOUT
    b353e0b41d588605958b03f9a223d10a2fbeb514
    FLAGS
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DONNX_CUSTOM_PROTOC_EXECUTABLE=${protoc_EXECUTABLE}
    -Donnxruntime_BUILD_SHARED_LIB=${SHARED}
    -Donnxruntime_BUILD_UNIT_TESTS=OFF
    -Donnxruntime_RUN_ONNX_TESTS=OFF
    -Donnxruntime_ENABLE_TRAINING=OFF
    -Donnxruntime_USE_XNNPACK=ON
)

### Error / output

/cache/linux/cmake/onnx_70481649_linux_20.04.5_x86_64/build/generated_source.c:3:10: fatal error: core/providers/xnnpack/xnnpack_provider_factory.h: No such file or directory
    3 | #include <core/providers/xnnpack/xnnpack_provider_factory.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by fs-eire** [comment]
`#include <core/providers/xnnpack/xnnpack_provider_factory.h>`

there is no such header file in the code base. where is this include line? should remove it or change it to xnnpack_provider_factory_creator.h

**Comment by wolfviking0** [comment]
Hi,

i think it could be something else in my side. Initially I was using 1.12.1 then move to 1.13.1

I seems this include come from a generated file, I suspect for some reason it did not regenerate this file or clean it.

i did a fresh clone and build on 1.13.1 and it seems to be working.

Thanks
