### ISSUE TITLE
how to build onnxruntime from source with dnnl? 

### ISSUE THREAD

**Issue by wangyunxiaa** [microsoft/onnxruntime#12011]
when I build onnxruntime with commond ./build.sh --config=MinSizeRel --minimal_build --build_shared_lib --use_dnnl --skip_tests --parallel, I got error The dependency target "onnxruntime_providers_shared" of target "onnxruntime_providers_dnnl" does not exist

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Centos
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:1.11.0
- Python version:3.8.5
- Visual Studio version (if applicable):NO
- GCC/Compiler version (if compiling from source):9.3.0
- CUDA/cuDNN version:No
- GPU model and memory:No

**Comment by ytaous** [comment]
is this what you followed? https://onnxruntime.ai/docs/build/eps.html#onednn
we have another example you can play with - https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/linux-dnnl-ci-pipeline.yml

**Comment by skottmckay** [comment]
It's not supported in a minimal build. What's the reason you added the `--minimal_build` flag?

**Comment by wangyunxiaa** [comment]
> It's not supported in a minimal build. What's the reason you added the `--minimal_build` flag?

because I got error without `--minimal_build` flag,
the error as ### https://github.com/microsoft/onnxruntime/issues/11547
I updated the gcc version to 10.2, but it does not work either

**Comment by wangyunxiaa** [comment]
> is this what you followed? https://onnxruntime.ai/docs/build/eps.html#onednn we have another example you can play with - https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/linux-dnnl-ci-pipeline.yml

Thanks, I will have a try

**Comment by wangyunxiaa** [comment]
> It's not supported in a minimal build. What's the reason you added the `--minimal_build` flag?
close the `--minimal_build` flag, I got some error as followings

```

/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc: At global scope:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1046:16: error: ‘onnx::OptionalProto::_Internal’ has not been declared
 1046 | OptionalProto::_Internal::map_value(const OptionalProto* msg) {
      |                ^~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc: In function ‘const onnx::MapProto& onnx::map_value(const onnx::OptionalProto*)’:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1047:14: error: invalid use of incomplete type ‘const class onnx::OptionalProto’
 1047 |   return *msg->map_value_;
      |              ^~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc: At global scope:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1050:16: error: ‘onnx::OptionalProto::_Internal’ has not been declared
 1050 | OptionalProto::_Internal::optional_value(const OptionalProto* msg) {
      |                ^~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc: In function ‘const onnx::OptionalProto& onnx::optional_value(const onnx::OptionalProto*)’:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1051:14: error: invalid use of incomplete type ‘const class onnx::OptionalProto’
 1051 |   return *msg->optional_value_;
      |              ^~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc: At global scope:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1053:40: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1053 | void OptionalProto::clear_tensor_value() {
      |                                        ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1057:47: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1057 | void OptionalProto::clear_sparse_tensor_value() {
      |                                               ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1062:47: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1062 |                          bool is_message_owned)
      |                                               ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1070:55: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1070 | OptionalProto::OptionalProto(const OptionalProto& from)
      |                                                       ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1108:32: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1108 | void OptionalProto::SharedCtor() {
      |                                ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1116:31: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1116 | OptionalProto::~OptionalProto() {
      |                               ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1123:39: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1123 | inline void OptionalProto::SharedDtor() {
      |                                       ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1133:43: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1133 | void OptionalProto::ArenaDtor(void* object) {
      |                                           ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1137:70: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1137 | void OptionalProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
      |                                                                      ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1139:45: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1139 | void OptionalProto::SetCachedSize(int size) const {
      |                                             ^~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1143:27: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1143 | void OptionalProto::Clear() {
      |                           ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1180:112: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1180 | const char* OptionalProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
      |                                                                                                                ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1270:103: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1270 |     ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
      |                                                                                                       ^~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1336:38: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1336 | size_t OptionalProto::ByteSizeLong() const {
      |                                      ^~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1403:53: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1403 |     const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
      |                                                     ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1408:56: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1408 | void OptionalProto::MergeFrom(const OptionalProto& from) {
      |                                                        ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1442:55: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1442 | void OptionalProto::CopyFrom(const OptionalProto& from) {
      |                                                       ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1449:37: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1449 | bool OptionalProto::IsInitialized() const {
      |                                     ^~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1453:54: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1453 | void OptionalProto::InternalSwap(OptionalProto* other) {
      |                                                      ^
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1472:42: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1472 | std::string OptionalProto::GetTypeName() const {
      |                                          ^~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/bits/move.h:55,
                 from /usr/include/c++/9/bits/stl_pair.h:59,
                 from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/string:40,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:8,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/usr/include/c++/9/type_traits: In instantiation of ‘struct std::is_trivially_destructible<onnx::SequenceProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36:   required from ‘class google::protobuf::Arena::InternalHelper<onnx::SequenceProto>’
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::SequenceProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1481:69:   required from here
/usr/include/c++/9/type_traits:1235:12: error: invalid use of incomplete type ‘class onnx::SequenceProto’
 1235 |     struct is_trivially_destructible
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:62:7: note: forward declaration of ‘class onnx::SequenceProto’
   62 | class SequenceProto;
      |       ^~~~~~~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:24,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘class google::protobuf::Arena::InternalHelper<onnx::SequenceProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::SequenceProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1481:69:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36: error: ‘value’ is not a member of ‘std::is_trivially_destructible<onnx::SequenceProto>’
  456 |         bool, sizeof(DestructorSkippable<T>(static_cast<const T*>(0))) ==
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |                       sizeof(char) ||
      |                       ~~~~~~~~~~~~~^~
  458 |                   std::is_trivially_destructible<T>::value>
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::SequenceProto]’:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1481:69:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52: error: static assertion failed: CreateMessage can only construct types that are ArenaConstructable
  543 |         InternalHelper<T>::is_arena_constructable::value,
      |                                                    ^~~~~
In file included from /usr/include/c++/9/bits/move.h:55,
                 from /usr/include/c++/9/bits/stl_pair.h:59,
                 from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/string:40,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:8,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/usr/include/c++/9/type_traits: In instantiation of ‘struct std::is_trivially_destructible<onnx::MapProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36:   required from ‘class google::protobuf::Arena::InternalHelper<onnx::MapProto>’
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::MapProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1484:64:   required from here
/usr/include/c++/9/type_traits:1235:12: error: invalid use of incomplete type ‘class onnx::MapProto’
 1235 |     struct is_trivially_destructible
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:56:7: note: forward declaration of ‘class onnx::MapProto’
   56 | class MapProto;
      |       ^~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:24,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘class google::protobuf::Arena::InternalHelper<onnx::MapProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::MapProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1484:64:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36: error: ‘value’ is not a member of ‘std::is_trivially_destructible<onnx::MapProto>’
  456 |         bool, sizeof(DestructorSkippable<T>(static_cast<const T*>(0))) ==
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |                       sizeof(char) ||
      |                       ~~~~~~~~~~~~~^~
  458 |                   std::is_trivially_destructible<T>::value>
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::MapProto]’:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1484:64:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52: error: static assertion failed: CreateMessage can only construct types that are ArenaConstructable
  543 |         InternalHelper<T>::is_arena_constructable::value,
      |                                                    ^~~~~
In file included from /usr/include/c++/9/bits/move.h:55,
                 from /usr/include/c++/9/bits/stl_pair.h:59,
                 from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/string:40,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:8,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/usr/include/c++/9/type_traits: In instantiation of ‘struct std::is_trivially_destructible<onnx::OptionalProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36:   required from ‘class google::protobuf::Arena::InternalHelper<onnx::OptionalProto>’
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::OptionalProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1487:69:   required from here
/usr/include/c++/9/type_traits:1235:12: error: invalid use of incomplete type ‘class onnx::OptionalProto’
 1235 |     struct is_trivially_destructible
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:59:7: note: forward declaration of ‘class onnx::OptionalProto’
   59 | class OptionalProto;
      |       ^~~~~~~~~~~~~
In file included from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.h:24,
                 from /models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:4:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘class google::protobuf::Arena::InternalHelper<onnx::OptionalProto>’:
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::OptionalProto]’
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1487:69:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:457:36: error: ‘value’ is not a member of ‘std::is_trivially_destructible<onnx::OptionalProto>’
  456 |         bool, sizeof(DestructorSkippable<T>(static_cast<const T*>(0))) ==
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  457 |                       sizeof(char) ||
      |                       ~~~~~~~~~~~~~^~
  458 |                   std::is_trivially_destructible<T>::value>
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = onnx::OptionalProto]’:
/models/onnxruntime/cmake/external/onnx/onnx/onnx-data.pb.cc:1487:69:   required from here
/models/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena.h:543:52: error: static assertion failed: CreateMessage can only construct types that are ArenaConstructable
  543 |         InternalHelper<T>::is_arena_constructable::value,
      |                                                    ^~~~~

```

**Comment by skottmckay** [comment]
Works on Ubuntu 20.04 which has GCC 9.4. Please check which gcc version your build is actually using. The CMake output will list this early on. Ubuntu 16.04 came with a much older version of gcc that most likely won't work.

`./build.sh --build_shared_lib --parallel --arm64 --use_dnnl --build_shared_lib --build_dir build/Linux.arm`

```
-- ******** Summary ********
--   CMake version             : 3.23.1
--   CMake command             : /home/s/cmake-3.23.1-linux-x86_64/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 9.4.0
```

**Comment by wangyunxiaa** [comment]
> Works on Ubuntu 20.04 which has GCC 9.4. Please check which gcc version your build is actually using. The CMake output will list this early on. Ubuntu 16.04 came with a much older version of gcc that most likely won't work.
> 
> `./build.sh --build_shared_lib --parallel --use_dnnl --build_shared_lib --build_dir build/Linux.arm`
> 
> ```
> -- ******** Summary ********
> --   CMake version             : 3.23.1
> --   CMake command             : /home/s/cmake-3.23.1-linux-x86_64/bin/cmake
> --   System                    : Linux
> --   C++ compiler              : /usr/bin/c++
> --   C++ compiler version      : 9.4.0
> ```

Thanks very much, my gcc version is 9.3.0 on ubuntu 18.04, I will update the env and have a try
